8 6


4   0 1 3 2 
4   0 2 6 4 
4   0 4 5 1 
4   1 5 7 3 
4   2 3 7 6 
4   4 6 7 5 
CartesianGrid2D(2,2,2)
1 cells
8 vertices

CartesianGrid2D(2,2,3)
2 cells
12 vertices

CartesianGrid2D(2,3,2)
2 cells
12 vertices

CartesianGrid2D(2,3,3)
4 cells
18 vertices

CartesianGrid2D(3,2,2)
2 cells
12 vertices

CartesianGrid2D(3,2,3)
4 cells
18 vertices

CartesianGrid2D(3,3,2)
4 cells
18 vertices

CartesianGrid2D(3,3,3)
8 cells
27 vertices

