#include "FunctionAlgebra/function-algebra.h"

#include "./write-code.h"


void RFunction::write_class(std::ostream& out, std::string const& name) const
{
 std::string varx("x");
 std::string varh("h");

 out << "////////////////////////////////////////////////\n"
     << "//\n"
     << "// Code automatically generated by class RFunction\n"
     << "//\n"
     << "////////////////////////////////////////////////\n\n\n"

     << "#include " << '"' << "FunctionAlgebra/RFunction.h" << '"' << "\n\n\n"
     << "#include " << '"' << "write_code.h" << '"' << "\n"

     << "class function_algebra_" << name << " : public function_algebra_impl {\n"
     << "private:\n"
     << "  coord_type derive(const coord_type& x, const coord_type& h) const;\n"
     << "public:\n"
     << "  function_algebra_" << name << "() {d_Def = " << dDef() << "; d_Im = " << dIm() <<";}\n"
     << "  std::string name() const { return " << '"' << "function_algebra_" << name << '"' << ";}\n"
     << "  coord_type eval(const coord_type& x) const;\n"
     << "  std::string write_code_eval(std::ostream& out, int& vnum, std::string const& var) const\n"
     << "  {return write_code_eval_libfct(out,vnum,var," << '"' << name << '"' << ");}\n"
     << "  std::string write_code_derive(std::ostream& out, int& vnum,\n"
     << "                          std::string const& varx, std::string const& varh) const\n"
     << "  {return write_code_derive_libfct(out,vnum,varx,varh," 
     << '"' << "d_" << name << '"' << ");}\n"
     << "};\n\n"
     << "inline coord_type " << "function_algebra_" << name << "::eval(const coord_type& " << varx << ") const\n"
     << "{\n";

 int vnum = 0;

 std::string result(write_code_eval(out,vnum,varx));
 out << "\n return(" << result << ");\n}\n\n";

 out << "inline coord_type " << "function_algebra_" << name << "::derive(const coord_type& " << varx 
     << ", const coord_type& " << varh << ") const\n"
     << "{\n";
 vnum = 0;
 std::string d_result(write_code_derive(out,vnum,varx,varh));
 out << "\n return(" << d_result << ");\n}\n\n";
}


std::string RFunction::write_code_eval(std::ostream& out, int& vnum, 
                                       std::string const& var) const
{
  std::string r(ff->write_code_eval(out,vnum,var));
  if(a!= 1.0 || ! IsNullvector(b)){
    std::string rr(makename("tmp",vnum++));
    std::string rtype( (dIm() == 1? "double" : "coord_type"));
    out << rtype << " " << rr << "(" << r << ");\n";
    if (a!= 1.0)
      out << rr << " *= " << a << ";\n";
    for (int i =1;i<= b.dim();i++)
      if( b[i] != 0)
	if(dIm() == 1)
	  out << rr << " += " << b[i] << ";\n";
	else
	  out << rr << "[" << i << "] += " << b[i] << ";\n";
    return rr;
  }
  else
    return  r;
}


std::string RFunction::write_code_derive(std::ostream& out, int& vnum, 
                                         std::string const& varx, 
                                         std::string const& varh) const
{
  std::string r(ff->write_code_derive(out,vnum,varx,varh));
  if(a != 1.0){
    std::string rr(makename("tmp",vnum++));
    std::string rtype( (dIm() == 1? "double" : "coord_type"));
    out << rtype << " " << rr << "(" << r << ");\n";
    out << rr << " *= " << a << ";\n";
    return rr;
  }
  return r;
}
