SUBDIRS = construct \
          conforming-leaf-grid \
          gridfunction \
          geometry \
          non-conforming-leaf-grid \
          octree \
          octree-leaf-iterator \
          table \


PWD=$(shell pwd)
CONFIG=$(PWD)/../mk.config

include  $(CONFIG)
include  $(RECURSIVETARGETS)



