Constructing subrange from 3x3 grid ...  done.
Subrange S: 4 cells, 9 vertices
Cells: C 0 = [0 0]  C 1 = [0 1]  C 2 = [1 0]  C 3 = [1 1]  
Vertices: V0 = [0 0]  V3 = [1 0]  V4 = [1 1]  V1 = [0 1]  V5 = [1 2]  V2 = [0 2]  V6 = [2 0]  V7 = [2 1]  V8 = [2 2]  

Piecemeal constructed subrange: 4 cells, 9 vertices
Cells: C0 = [0 0]  C1 = [0 1]  C2 = [1 0]  C3 = [1 1]  
Vertices: V0 = [0 0]  V3 = [1 0]  V4 = [1 1]  V1 = [0 1]  V5 = [1 2]  V2 = [0 2]  V6 = [2 0]  V7 = [2 1]  V8 = [2 2]  

Copied subrange: 4 cells, 9 vertices
Cells: C0 = [0 0]  C1 = [0 1]  C2 = [1 0]  C3 = [1 1]  
Vertices: V0 = [0 0]  V3 = [1 0]  V4 = [1 1]  V1 = [0 1]  V5 = [1 2]  V2 = [0 2]  V6 = [2 0]  V7 = [2 1]  V8 = [2 2]  

Empty subrange: 0 cells, 0 vertices
Cells: 
Vertices: 
