export CONFIG:=$(PWD)/mk.config
unexport PWD
include $(CONFIG)


TARGET=all

all:

new: clean


compile:

lib:

#DIRS =  base complex2d distributed partitioning

SHELL=/bin/bash

install-headers:

clean: stdclean
	rm -f doxy.tags doxy.log

realclean: clean
	rm -rf doxygen/

test:


doc: doxy


