CONFIG=$(shell pwd)/../mk.config

SUBDIRS = bijective-mapping  \
          bivector \
          bubblesort \
          combinatorial \
          histogram \
          index-map-nd \
          integer-range \
          sequence-algorithms \
          tuple \
          union-find \


include  $(CONFIG)
include  $(RECURSIVETARGETS)



