CONFIG=$(shell pwd)/../local.config

SUBDIRS = bijective-mapping  \
          bivector \
          bubblesort \
          combinatorial \
          counting-iterator \
          histogram \
          index-map-nd \
          integer-range \
          sequence-algorithms \
          tuple \
          union-find \


include  $(CONFIG)
include  $(RECURSIVETARGETS)



