SUBDIRS = bijective-mapping  \
          bivector \
          bubblesort \
          combinatorial \
          histogram \
          index-map-nd \
          integer-range \
          sequence-algorithms \
          tuple 

include  $(CONFIG)
include  $(RECURSIVETARGETS)



