Poly 0: 0 0
Poly 1: 0 0 -> 0.25 0
Poly 2: 0 0 -> 0.25 0 -> 0.25 0.25 -> 0 0.25
directions 0: 
directions 1: 
directions 2: 
p0 and p2 do  intersect
p1 and p2 do  intersect
p2 and p2 do  intersect
p0 and p1 do  intersect
p0 and p2B do not intersect
p1 and p2B do not intersect
p2 and p2B do not intersect
Poly 0: 0 0 0
Poly 1: 0 0 0 -> 0.25 0 0
Poly 2: 0 0 0 -> 0.25 0 0 -> 0.25 0.25 0 -> 0 0.25 0
Poly 3: 0 0 0 -> 0 0 0.25 -> 0 0.25 0 -> 0 0.25 0.25 -> 0.25 0 0 -> 0.25 0 0.25 -> 0.25 0.25 0 -> 0.25 0.25 0.25
p0 and p1 do  intersect
p0 and p2 do  intersect
p0 and p3 do  intersect
p1 and p1 do  intersect
p1 and p2 do  intersect
p1 and p3 do  intersect
p2 and p2 do  intersect
p2 and p3 do  intersect
p3 and p3 do  intersect
p0 and p3B do not intersect
p1 and p3B do not intersect
p2 and p3B do not intersect
p3 and p3B do  intersect
