
Testing 1D maps
===============
Testing map: n = -1
  min_flat_index()=0  max_flat_index()=-2  min_tuple()=0  max_tuple()=-2  beyond_tuple()=-1  size() =-1

Testing map: n = 0
  min_flat_index()=0  max_flat_index()=-1  min_tuple()=0  max_tuple()=-1  beyond_tuple()=0  size() =0

Testing map: n = 1
  min_flat_index()=0  max_flat_index()=0  min_tuple()=0  max_tuple()=0  beyond_tuple()=1  size() =1
i= 0 map(i)= 0

Testing map: n = 5
  min_flat_index()=0  max_flat_index()=4  min_tuple()=0  max_tuple()=4  beyond_tuple()=5  size() =5
i= 0 map(i)= 0
i= 1 map(i)= 1
i= 2 map(i)= 2
i= 3 map(i)= 3
i= 4 map(i)= 4


Testing 2D maps
===============
Testing map: n = -1 -1
  min_flat_index()=0  max_flat_index()=-1  min_tuple()=0 0  max_tuple()=-2 -2  beyond_tuple()=-1 -1  size() =-1 -1

Testing map: n = 0 0
  min_flat_index()=0  max_flat_index()=-1  min_tuple()=0 0  max_tuple()=-1 -1  beyond_tuple()=0 0  size() =0 0

Testing map: n = 1 0
  min_flat_index()=0  max_flat_index()=-1  min_tuple()=0 0  max_tuple()=0 -1  beyond_tuple()=1 0  size() =1 0

Testing map: n = 1 1
  min_flat_index()=0  max_flat_index()=0  min_tuple()=0 0  max_tuple()=0 0  beyond_tuple()=1 1  size() =1 1
i= 0 map(i)= 0 0

Testing map: n = 2 1
  min_flat_index()=0  max_flat_index()=1  min_tuple()=0 0  max_tuple()=1 0  beyond_tuple()=2 1  size() =2 1
i= 0 map(i)= 0 0
i= 1 map(i)= 1 0


Testing 3D maps
===============
Testing map: n = 0 0 0
  min_flat_index()=0  max_flat_index()=-1  min_tuple()=0 0 0  max_tuple()=-1 -1 -1  beyond_tuple()=0 0 0  size() =0 0 0

Testing map: n = 1 1 1
  min_flat_index()=0  max_flat_index()=0  min_tuple()=0 0 0  max_tuple()=0 0 0  beyond_tuple()=1 1 1  size() =1 1 1
i= 0 map(i)= 0 0 0

Testing map: n = 1 2 3
  min_flat_index()=0  max_flat_index()=5  min_tuple()=0 0 0  max_tuple()=0 1 2  beyond_tuple()=1 2 3  size() =1 2 3
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 0 1
i= 2 map(i)= 0 0 2
i= 3 map(i)= 0 1 0
i= 4 map(i)= 0 1 1
i= 5 map(i)= 0 1 2

Testing map: n = 3 2 1
  min_flat_index()=0  max_flat_index()=5  min_tuple()=0 0 0  max_tuple()=2 1 0  beyond_tuple()=3 2 1  size() =3 2 1
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 1 0
i= 2 map(i)= 1 0 0
i= 3 map(i)= 1 1 0
i= 4 map(i)= 2 0 0
i= 5 map(i)= 2 1 0

Testing map: n = 2 3 4
  min_flat_index()=0  max_flat_index()=23  min_tuple()=0 0 0  max_tuple()=1 2 3  beyond_tuple()=2 3 4  size() =2 3 4
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 0 1
i= 2 map(i)= 0 0 2
i= 3 map(i)= 0 0 3
i= 4 map(i)= 0 1 0
i= 5 map(i)= 0 1 1
i= 6 map(i)= 0 1 2
i= 7 map(i)= 0 1 3
i= 8 map(i)= 0 2 0
i= 9 map(i)= 0 2 1
i= 10 map(i)= 0 2 2
i= 11 map(i)= 0 2 3
i= 12 map(i)= 1 0 0
i= 13 map(i)= 1 0 1
i= 14 map(i)= 1 0 2
i= 15 map(i)= 1 0 3
i= 16 map(i)= 1 1 0
i= 17 map(i)= 1 1 1
i= 18 map(i)= 1 1 2
i= 19 map(i)= 1 1 3
i= 20 map(i)= 1 2 0
i= 21 map(i)= 1 2 1
i= 22 map(i)= 1 2 2
i= 23 map(i)= 1 2 3

Testing map: low = 1 1 1 beyond = 2 2 2
  min_flat_index()=0  max_flat_index()=0  min_tuple()=1 1 1  max_tuple()=1 1 1  beyond_tuple()=2 2 2  size() =1 1 1
i= 0 map(i)= 1 1 1

Testing map: low = 1 1 1 beyond = 3 3 3
  min_flat_index()=0  max_flat_index()=7  min_tuple()=1 1 1  max_tuple()=2 2 2  beyond_tuple()=3 3 3  size() =2 2 2
i= 0 map(i)= 1 1 1
i= 1 map(i)= 1 1 2
i= 2 map(i)= 1 2 1
i= 3 map(i)= 1 2 2
i= 4 map(i)= 2 1 1
i= 5 map(i)= 2 1 2
i= 6 map(i)= 2 2 1
i= 7 map(i)= 2 2 2

