
Testing 1D maps
===============
Testing map: n = -1
map.min_flat_index()=0 map.max_flat_index()=-2 map.max_tuple()= -2

Testing map: n = 0
map.min_flat_index()=0 map.max_flat_index()=-1 map.max_tuple()= -1

Testing map: n = 1
map.min_flat_index()=0 map.max_flat_index()=0 map.max_tuple()= 0
i= 0 map(i)= 0

Testing map: n = 5
map.min_flat_index()=0 map.max_flat_index()=4 map.max_tuple()= 4
i= 0 map(i)= 0
i= 1 map(i)= 1
i= 2 map(i)= 2
i= 3 map(i)= 3
i= 4 map(i)= 4


Testing 2D maps
===============
Testing map: n = -1 -1
map.min_flat_index()=0 map.max_flat_index()=-1 map.max_tuple()= -2 -2

Testing map: n = 0 0
map.min_flat_index()=0 map.max_flat_index()=-1 map.max_tuple()= -1 -1

Testing map: n = 1 0
map.min_flat_index()=0 map.max_flat_index()=-1 map.max_tuple()= 0 -1

Testing map: n = 1 1
map.min_flat_index()=0 map.max_flat_index()=0 map.max_tuple()= 0 0
i= 0 map(i)= 0 0

Testing map: n = 2 1
map.min_flat_index()=0 map.max_flat_index()=1 map.max_tuple()= 1 0
i= 0 map(i)= 0 0
i= 1 map(i)= 1 0


Testing 3D maps
===============
Testing map: n = 0 0 0
map.min_flat_index()=0 map.max_flat_index()=-1 map.max_tuple()= -1 -1 -1

Testing map: n = 1 1 1
map.min_flat_index()=0 map.max_flat_index()=0 map.max_tuple()= 0 0 0
i= 0 map(i)= 0 0 0

Testing map: n = 1 2 3
map.min_flat_index()=0 map.max_flat_index()=5 map.max_tuple()= 0 1 2
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 0 1
i= 2 map(i)= 0 0 2
i= 3 map(i)= 0 1 0
i= 4 map(i)= 0 1 1
i= 5 map(i)= 0 1 2

Testing map: n = 3 2 1
map.min_flat_index()=0 map.max_flat_index()=5 map.max_tuple()= 2 1 0
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 1 0
i= 2 map(i)= 1 0 0
i= 3 map(i)= 1 1 0
i= 4 map(i)= 2 0 0
i= 5 map(i)= 2 1 0

Testing map: n = 2 3 4
map.min_flat_index()=0 map.max_flat_index()=23 map.max_tuple()= 1 2 3
i= 0 map(i)= 0 0 0
i= 1 map(i)= 0 0 1
i= 2 map(i)= 0 0 2
i= 3 map(i)= 0 0 3
i= 4 map(i)= 0 1 0
i= 5 map(i)= 0 1 1
i= 6 map(i)= 0 1 2
i= 7 map(i)= 0 1 3
i= 8 map(i)= 0 2 0
i= 9 map(i)= 0 2 1
i= 10 map(i)= 0 2 2
i= 11 map(i)= 0 2 3
i= 12 map(i)= 1 0 0
i= 13 map(i)= 1 0 1
i= 14 map(i)= 1 0 2
i= 15 map(i)= 1 0 3
i= 16 map(i)= 1 1 0
i= 17 map(i)= 1 1 1
i= 18 map(i)= 1 1 2
i= 19 map(i)= 1 1 3
i= 20 map(i)= 1 2 0
i= 21 map(i)= 1 2 1
i= 22 map(i)= 1 2 2
i= 23 map(i)= 1 2 3

