Testing binomial coefficient:
0       1 
1      1 1 
2     1 2 1 
3    1 3 3 1 
4   1 4 6 4 1 
Testing succ_ordered maxitem = 1 (empty v):
 -> 
Testing succ_ordered maxitem = 0:
0  -> 
Testing succ_ordered maxitem = 1:
0  -> 1  -> 
Testing succ_ordered maxitem = 3:
0 1  -> 0 2  -> 0 3  -> 1 2  -> 1 3  -> 2 3  -> 
Testing succ_nary_number(v,2) (empty v):
 -> 
Testing succ_nary_number(v,2):
0  -> 1  -> 
Testing succ_nary_number(v,2):
0 0 0  -> 0 0 1  -> 0 1 0  -> 0 1 1  -> 1 0 0  -> 1 0 1  -> 1 1 0  -> 1 1 1  -> 
Testing succ_nary_number(v,3):
0 0  -> 0 1  -> 0 2  -> 1 0  -> 1 1  -> 1 2  -> 2 0  -> 2 1  -> 2 2  -> 
