Testing power:
power<2,0>=1
power<2,1>=2
power<2,31>=2147483648
power<2,32>=0
Testing factorial:
factorial(0)=1
factorial(1)=1
factorial(2)=2
factorial(3)=6
factorial(4)=24
factorial(5)=120
factorial(6)=720
factorial(7)=5040
factorial(8)=40320
factorial(9)=362880
factorial(10)=3628800
factorial(11)=39916800
factorial(12)=479001600
factorial(13)=1932053504
factorial(14)=1278945280
factorial(15)=2004310016
Testing binomial coefficient:
0       1 
1      1 1 
2     1 2 1 
3    1 3 3 1 
4   1 4 6 4 1 
Testing succ_ordered maxitem = 1 (empty v):
 -> 
Testing succ_ordered maxitem = 0:
0  -> 
Testing succ_ordered maxitem = 1:
0  -> 1  -> 
Testing succ_ordered maxitem = 3:
0 1  -> 0 2  -> 0 3  -> 1 2  -> 1 3  -> 2 3  -> 
Testing succ_nary_number(v,2) (empty v):
 -> 
Testing succ_nary_number(v,2):
0  -> 1  -> 
Testing succ_nary_number(v,2):
0 0 0  -> 0 0 1  -> 0 1 0  -> 0 1 1  -> 1 0 0  -> 1 0 1  -> 1 1 0  -> 1 1 1  -> 
Testing succ_nary_number(v,3):
0 0  -> 0 1  -> 0 2  -> 1 0  -> 1 1  -> 1 2  -> 2 0  -> 2 1  -> 2 2  -> 
