
PWD=$(shell pwd)
CONFIG=$(PWD)/../local.config

SUBDIRS = bucketing \
          geometric-field \
          enclosed-volume \
          intersection-ray-grid \
          linear-cube \
          linear-simplex \
          point-locator \
          vertex-normals

include  $(CONFIG)
include  $(RECURSIVETARGETS)




