
PWD=$(shell pwd)
CONFIG=$(PWD)/../local.config

SUBDIRS = bucketing \
          geometric-field \
          intersection-ray-grid \
          linear-cube \
          linear-simplex \
          point-locator

include  $(CONFIG)
include  $(RECURSIVETARGETS)




