constructing Complex2D CC[0] from file grid.in
constructing Complex2D CC[1] from CC[0]
constructing Complex2D CC[2] from file (2 times) grid.in
leaving CC[3] empty 
9 4

0 0
0 0.5
0 1
0.5 0
0.5 0.5
0.5 1
1 0
1 0.5
1 1

4   1 4 5 2 
4   2 5 6 3 
4   4 7 8 5 
4   5 8 9 6 
9 4

0 0
0 0.5
0 1
0.5 0
0.5 0.5
0.5 1
1 0
1 0.5
1 1

4   1 4 5 2 
4   2 5 6 3 
4   4 7 8 5 
4   5 8 9 6 
9 4

0 0
0 0.5
0 1
0.5 0
0.5 0.5
0.5 1
1 0
1 0.5
1 1

4   1 4 5 2 
4   2 5 6 3 
4   4 7 8 5 
4   5 8 9 6 
0 0


Testing CC[0]
9 vertices,  4 cells.
Vertex 0 has 1 adj. Cells: ( No. 1, center 0.25 0.25)  
Vertex 1 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  
Vertex 2 has 1 adj. Cells: ( No. 2, center 0.25 0.75)  
Vertex 3 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 3, center 0.75 0.25)  
Vertex 4 has 4 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 5 has 2 adj. Cells: ( No. 2, center 0.25 0.75)  ( No. 4, center 0.75 0.75)  
Vertex 6 has 1 adj. Cells: ( No. 3, center 0.75 0.25)  
Vertex 7 has 2 adj. Cells: ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 8 has 1 adj. Cells: ( No. 4, center 0.75 0.75)  
Cell 1 has volume 0.25; 4  Vertices:  0 3 4 1  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 3 -> 4;  Edge(*nb,*c) : 4 -> 3;  Edge(nb) : 3 -> 4]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 3 v2: 4 
e   =                         3 -> 4
e1  = Flip(v1,e):             0 -> 3;  e2  = Flip(v2,e):             4 -> 1
e12 = Flip(e1.V2(),e1) ( == e)3 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)3 -> 4
      outward normal = 1 -0
    2 :[ Edge(*c,*nb) : 4 -> 1;  Edge(*nb,*c) : 1 -> 4;  Edge(nb) : 4 -> 1]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 4 v2: 1 
e   =                         4 -> 1
e1  = Flip(v1,e):             3 -> 4;  e2  = Flip(v2,e):             1 -> 0
e12 = Flip(e1.V2(),e1) ( == e)4 -> 1;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 1
      outward normal = 0 1

  Edges:   No. 1 : (0 0,0.5 0),  No. 2 : (0.5 0,0.5 0.5),  No. 3 : (0.5 0.5,0 0.5),  No. 4 : (0 0.5,0 0), 
Cell 2 has volume 0.25; 4  Vertices:  1 4 5 2  and 2 Nbs': 
    1 :[ Edge(*c,*nb) : 1 -> 4;  Edge(*nb,*c) : 4 -> 1;  Edge(nb) : 1 -> 4]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 1 v2: 4 
e   =                         1 -> 4
e1  = Flip(v1,e):             2 -> 1;  e2  = Flip(v2,e):             4 -> 5
e12 = Flip(e1.V2(),e1) ( == e)1 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)1 -> 4
      outward normal = 0 -1
    4 :[ Edge(*c,*nb) : 4 -> 5;  Edge(*nb,*c) : 5 -> 4;  Edge(nb) : 4 -> 5]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 4 v2: 5 
e   =                         4 -> 5
e1  = Flip(v1,e):             1 -> 4;  e2  = Flip(v2,e):             5 -> 2
e12 = Flip(e1.V2(),e1) ( == e)4 -> 5;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 5
      outward normal = 1 -0

  Edges:   No. 1 : (0 0.5,0.5 0.5),  No. 2 : (0.5 0.5,0.5 1),  No. 3 : (0.5 1,0 1),  No. 4 : (0 1,0 0.5), 
Cell 3 has volume 0.25; 4  Vertices:  3 6 7 4  and 2 Nbs': 
    4 :[ Edge(*c,*nb) : 7 -> 4;  Edge(*nb,*c) : 4 -> 7;  Edge(nb) : 7 -> 4]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 7 v2: 4 
e   =                         7 -> 4
e1  = Flip(v1,e):             6 -> 7;  e2  = Flip(v2,e):             4 -> 3
e12 = Flip(e1.V2(),e1) ( == e)7 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)7 -> 4
      outward normal = 0 1
    1 :[ Edge(*c,*nb) : 4 -> 3;  Edge(*nb,*c) : 3 -> 4;  Edge(nb) : 4 -> 3]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 4 v2: 3 
e   =                         4 -> 3
e1  = Flip(v1,e):             7 -> 4;  e2  = Flip(v2,e):             3 -> 6
e12 = Flip(e1.V2(),e1) ( == e)4 -> 3;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 3
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0,1 0),  No. 2 : (1 0,1 0.5),  No. 3 : (1 0.5,0.5 0.5),  No. 4 : (0.5 0.5,0.5 0), 
Cell 4 has volume 0.25; 4  Vertices:  4 7 8 5  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 4 -> 7;  Edge(*nb,*c) : 7 -> 4;  Edge(nb) : 4 -> 7]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 4 v2: 7 
e   =                         4 -> 7
e1  = Flip(v1,e):             5 -> 4;  e2  = Flip(v2,e):             7 -> 8
e12 = Flip(e1.V2(),e1) ( == e)4 -> 7;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 7
      outward normal = 0 -1
    2 :[ Edge(*c,*nb) : 5 -> 4;  Edge(*nb,*c) : 4 -> 5;  Edge(nb) : 5 -> 4]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 5 v2: 4 
e   =                         5 -> 4
e1  = Flip(v1,e):             8 -> 5;  e2  = Flip(v2,e):             4 -> 7
e12 = Flip(e1.V2(),e1) ( == e)5 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)5 -> 4
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0.5,1 0.5),  No. 2 : (1 0.5,1 1),  No. 3 : (1 1,0.5 1),  No. 4 : (0.5 1,0.5 0.5), 
Edge [0 <-> 3]    [0 0 <-> 0.5 0]  adj. cells: 1,-1   volume = 0.5 normal = -0 1
Edge [1 <-> 0]    [0 0.5 <-> 0 0]  adj. cells: 1,-1   volume = 0.5 normal = 1 0
Edge [1 <-> 4]    [0 0.5 <-> 0.5 0.5]  adj. cells: 2,1   volume = 0.5 normal = -0 1
Edge [5 <-> 2]    [0.5 1 <-> 0 1]  adj. cells: 2,-1   volume = 0.5 normal = -0 -1
Edge [2 <-> 1]    [0 1 <-> 0 0.5]  adj. cells: 2,-1   volume = 0.5 normal = 1 0
Edge [3 <-> 6]    [0.5 0 <-> 1 0]  adj. cells: 3,-1   volume = 0.5 normal = -0 1
Edge [6 <-> 7]    [1 0 <-> 1 0.5]  adj. cells: 3,-1   volume = 0.5 normal = -1 0
Edge [4 <-> 3]    [0.5 0.5 <-> 0.5 0]  adj. cells: 3,1   volume = 0.5 normal = 1 0
Edge [4 <-> 7]    [0.5 0.5 <-> 1 0.5]  adj. cells: 4,3   volume = 0.5 normal = -0 1
Edge [7 <-> 8]    [1 0.5 <-> 1 1]  adj. cells: 4,-1   volume = 0.5 normal = -1 0
Edge [8 <-> 5]    [1 1 <-> 0.5 1]  adj. cells: 4,-1   volume = 0.5 normal = -0 -1
Edge [5 <-> 4]    [0.5 1 <-> 0.5 0.5]  adj. cells: 4,2   volume = 0.5 normal = 1 0

Boundary-Edges: 
Edge (0 0.5,0 0)
Edge (0 0,0.5 0)
Edge (0 1,0 0.5)
Edge (0.5 1,0 1)
Edge (0.5 0,1 0)
Edge (1 1,0.5 1)
Edge (1 0,1 0.5)
Edge (1 0.5,1 1)

-----------------------------------------------------------
                       boundary
-----------------------------------------------------------

Boundary-Edges:
# 0  (V1,V2) =  (1,0)  coords =  (0 0.5,0 0)
# 1  (V1,V2) =  (0,3)  coords =  (0 0,0.5 0)
# 2  (V1,V2) =  (3,6)  coords =  (0.5 0,1 0)
# 3  (V1,V2) =  (6,7)  coords =  (1 0,1 0.5)
# 4  (V1,V2) =  (7,8)  coords =  (1 0.5,1 1)
# 5  (V1,V2) =  (8,5)  coords =  (1 1,0.5 1)
# 6  (V1,V2) =  (5,2)  coords =  (0.5 1,0 1)
# 7  (V1,V2) =  (2,1)  coords =  (0 1,0 0.5)


Boundary Vertices:
# 0  VNum = 0  coord = 0 0
# 1  VNum = 3  coord = 0.5 0
# 2  VNum = 6  coord = 1 0
# 3  VNum = 7  coord = 1 0.5
# 4  VNum = 8  coord = 1 1
# 5  VNum = 5  coord = 0.5 1
# 6  VNum = 2  coord = 0 1
# 7  VNum = 1  coord = 0 0.5

---------------------------------------------------
---------------------------------------------------

Testing CC[1]
9 vertices,  4 cells.
Vertex 0 has 1 adj. Cells: ( No. 1, center 0.25 0.25)  
Vertex 1 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  
Vertex 2 has 1 adj. Cells: ( No. 2, center 0.25 0.75)  
Vertex 3 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 3, center 0.75 0.25)  
Vertex 4 has 4 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 5 has 2 adj. Cells: ( No. 2, center 0.25 0.75)  ( No. 4, center 0.75 0.75)  
Vertex 6 has 1 adj. Cells: ( No. 3, center 0.75 0.25)  
Vertex 7 has 2 adj. Cells: ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 8 has 1 adj. Cells: ( No. 4, center 0.75 0.75)  
Cell 1 has volume 0.25; 4  Vertices:  0 3 4 1  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 3 -> 4;  Edge(*nb,*c) : 4 -> 3;  Edge(nb) : 3 -> 4]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 3 v2: 4 
e   =                         3 -> 4
e1  = Flip(v1,e):             0 -> 3;  e2  = Flip(v2,e):             4 -> 1
e12 = Flip(e1.V2(),e1) ( == e)3 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)3 -> 4
      outward normal = 1 -0
    2 :[ Edge(*c,*nb) : 4 -> 1;  Edge(*nb,*c) : 1 -> 4;  Edge(nb) : 4 -> 1]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 4 v2: 1 
e   =                         4 -> 1
e1  = Flip(v1,e):             3 -> 4;  e2  = Flip(v2,e):             1 -> 0
e12 = Flip(e1.V2(),e1) ( == e)4 -> 1;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 1
      outward normal = 0 1

  Edges:   No. 1 : (0 0,0.5 0),  No. 2 : (0.5 0,0.5 0.5),  No. 3 : (0.5 0.5,0 0.5),  No. 4 : (0 0.5,0 0), 
Cell 2 has volume 0.25; 4  Vertices:  1 4 5 2  and 2 Nbs': 
    1 :[ Edge(*c,*nb) : 1 -> 4;  Edge(*nb,*c) : 4 -> 1;  Edge(nb) : 1 -> 4]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 1 v2: 4 
e   =                         1 -> 4
e1  = Flip(v1,e):             2 -> 1;  e2  = Flip(v2,e):             4 -> 5
e12 = Flip(e1.V2(),e1) ( == e)1 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)1 -> 4
      outward normal = 0 -1
    4 :[ Edge(*c,*nb) : 4 -> 5;  Edge(*nb,*c) : 5 -> 4;  Edge(nb) : 4 -> 5]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 4 v2: 5 
e   =                         4 -> 5
e1  = Flip(v1,e):             1 -> 4;  e2  = Flip(v2,e):             5 -> 2
e12 = Flip(e1.V2(),e1) ( == e)4 -> 5;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 5
      outward normal = 1 -0

  Edges:   No. 1 : (0 0.5,0.5 0.5),  No. 2 : (0.5 0.5,0.5 1),  No. 3 : (0.5 1,0 1),  No. 4 : (0 1,0 0.5), 
Cell 3 has volume 0.25; 4  Vertices:  3 6 7 4  and 2 Nbs': 
    4 :[ Edge(*c,*nb) : 7 -> 4;  Edge(*nb,*c) : 4 -> 7;  Edge(nb) : 7 -> 4]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 7 v2: 4 
e   =                         7 -> 4
e1  = Flip(v1,e):             6 -> 7;  e2  = Flip(v2,e):             4 -> 3
e12 = Flip(e1.V2(),e1) ( == e)7 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)7 -> 4
      outward normal = 0 1
    1 :[ Edge(*c,*nb) : 4 -> 3;  Edge(*nb,*c) : 3 -> 4;  Edge(nb) : 4 -> 3]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 4 v2: 3 
e   =                         4 -> 3
e1  = Flip(v1,e):             7 -> 4;  e2  = Flip(v2,e):             3 -> 6
e12 = Flip(e1.V2(),e1) ( == e)4 -> 3;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 3
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0,1 0),  No. 2 : (1 0,1 0.5),  No. 3 : (1 0.5,0.5 0.5),  No. 4 : (0.5 0.5,0.5 0), 
Cell 4 has volume 0.25; 4  Vertices:  4 7 8 5  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 4 -> 7;  Edge(*nb,*c) : 7 -> 4;  Edge(nb) : 4 -> 7]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 4 v2: 7 
e   =                         4 -> 7
e1  = Flip(v1,e):             5 -> 4;  e2  = Flip(v2,e):             7 -> 8
e12 = Flip(e1.V2(),e1) ( == e)4 -> 7;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 7
      outward normal = 0 -1
    2 :[ Edge(*c,*nb) : 5 -> 4;  Edge(*nb,*c) : 4 -> 5;  Edge(nb) : 5 -> 4]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 5 v2: 4 
e   =                         5 -> 4
e1  = Flip(v1,e):             8 -> 5;  e2  = Flip(v2,e):             4 -> 7
e12 = Flip(e1.V2(),e1) ( == e)5 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)5 -> 4
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0.5,1 0.5),  No. 2 : (1 0.5,1 1),  No. 3 : (1 1,0.5 1),  No. 4 : (0.5 1,0.5 0.5), 
Edge [0 <-> 3]    [0 0 <-> 0.5 0]  adj. cells: 1,-1   volume = 0.5 normal = -0 1
Edge [1 <-> 0]    [0 0.5 <-> 0 0]  adj. cells: 1,-1   volume = 0.5 normal = 1 0
Edge [1 <-> 4]    [0 0.5 <-> 0.5 0.5]  adj. cells: 2,1   volume = 0.5 normal = -0 1
Edge [5 <-> 2]    [0.5 1 <-> 0 1]  adj. cells: 2,-1   volume = 0.5 normal = -0 -1
Edge [2 <-> 1]    [0 1 <-> 0 0.5]  adj. cells: 2,-1   volume = 0.5 normal = 1 0
Edge [3 <-> 6]    [0.5 0 <-> 1 0]  adj. cells: 3,-1   volume = 0.5 normal = -0 1
Edge [6 <-> 7]    [1 0 <-> 1 0.5]  adj. cells: 3,-1   volume = 0.5 normal = -1 0
Edge [4 <-> 3]    [0.5 0.5 <-> 0.5 0]  adj. cells: 3,1   volume = 0.5 normal = 1 0
Edge [4 <-> 7]    [0.5 0.5 <-> 1 0.5]  adj. cells: 4,3   volume = 0.5 normal = -0 1
Edge [7 <-> 8]    [1 0.5 <-> 1 1]  adj. cells: 4,-1   volume = 0.5 normal = -1 0
Edge [8 <-> 5]    [1 1 <-> 0.5 1]  adj. cells: 4,-1   volume = 0.5 normal = -0 -1
Edge [5 <-> 4]    [0.5 1 <-> 0.5 0.5]  adj. cells: 4,2   volume = 0.5 normal = 1 0

Boundary-Edges: 
Edge (0 0.5,0 0)
Edge (0 0,0.5 0)
Edge (0 1,0 0.5)
Edge (0.5 1,0 1)
Edge (0.5 0,1 0)
Edge (1 1,0.5 1)
Edge (1 0,1 0.5)
Edge (1 0.5,1 1)

-----------------------------------------------------------
                       boundary
-----------------------------------------------------------

Boundary-Edges:
# 0  (V1,V2) =  (1,0)  coords =  (0 0.5,0 0)
# 1  (V1,V2) =  (0,3)  coords =  (0 0,0.5 0)
# 2  (V1,V2) =  (3,6)  coords =  (0.5 0,1 0)
# 3  (V1,V2) =  (6,7)  coords =  (1 0,1 0.5)
# 4  (V1,V2) =  (7,8)  coords =  (1 0.5,1 1)
# 5  (V1,V2) =  (8,5)  coords =  (1 1,0.5 1)
# 6  (V1,V2) =  (5,2)  coords =  (0.5 1,0 1)
# 7  (V1,V2) =  (2,1)  coords =  (0 1,0 0.5)


Boundary Vertices:
# 0  VNum = 0  coord = 0 0
# 1  VNum = 3  coord = 0.5 0
# 2  VNum = 6  coord = 1 0
# 3  VNum = 7  coord = 1 0.5
# 4  VNum = 8  coord = 1 1
# 5  VNum = 5  coord = 0.5 1
# 6  VNum = 2  coord = 0 1
# 7  VNum = 1  coord = 0 0.5

---------------------------------------------------
---------------------------------------------------

Testing CC[2]
9 vertices,  4 cells.
Vertex 0 has 1 adj. Cells: ( No. 1, center 0.25 0.25)  
Vertex 1 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  
Vertex 2 has 1 adj. Cells: ( No. 2, center 0.25 0.75)  
Vertex 3 has 2 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 3, center 0.75 0.25)  
Vertex 4 has 4 adj. Cells: ( No. 1, center 0.25 0.25)  ( No. 2, center 0.25 0.75)  ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 5 has 2 adj. Cells: ( No. 2, center 0.25 0.75)  ( No. 4, center 0.75 0.75)  
Vertex 6 has 1 adj. Cells: ( No. 3, center 0.75 0.25)  
Vertex 7 has 2 adj. Cells: ( No. 3, center 0.75 0.25)  ( No. 4, center 0.75 0.75)  
Vertex 8 has 1 adj. Cells: ( No. 4, center 0.75 0.75)  
Cell 1 has volume 0.25; 4  Vertices:  0 3 4 1  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 3 -> 4;  Edge(*nb,*c) : 4 -> 3;  Edge(nb) : 3 -> 4]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 3 v2: 4 
e   =                         3 -> 4
e1  = Flip(v1,e):             0 -> 3;  e2  = Flip(v2,e):             4 -> 1
e12 = Flip(e1.V2(),e1) ( == e)3 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)3 -> 4
      outward normal = 1 -0
    2 :[ Edge(*c,*nb) : 4 -> 1;  Edge(*nb,*c) : 1 -> 4;  Edge(nb) : 4 -> 1]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 4 v2: 1 
e   =                         4 -> 1
e1  = Flip(v1,e):             3 -> 4;  e2  = Flip(v2,e):             1 -> 0
e12 = Flip(e1.V2(),e1) ( == e)4 -> 1;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 1
      outward normal = 0 1

  Edges:   No. 1 : (0 0,0.5 0),  No. 2 : (0.5 0,0.5 0.5),  No. 3 : (0.5 0.5,0 0.5),  No. 4 : (0 0.5,0 0), 
Cell 2 has volume 0.25; 4  Vertices:  1 4 5 2  and 2 Nbs': 
    1 :[ Edge(*c,*nb) : 1 -> 4;  Edge(*nb,*c) : 4 -> 1;  Edge(nb) : 1 -> 4]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 1 v2: 4 
e   =                         1 -> 4
e1  = Flip(v1,e):             2 -> 1;  e2  = Flip(v2,e):             4 -> 5
e12 = Flip(e1.V2(),e1) ( == e)1 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)1 -> 4
      outward normal = 0 -1
    4 :[ Edge(*c,*nb) : 4 -> 5;  Edge(*nb,*c) : 5 -> 4;  Edge(nb) : 4 -> 5]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 4 v2: 5 
e   =                         4 -> 5
e1  = Flip(v1,e):             1 -> 4;  e2  = Flip(v2,e):             5 -> 2
e12 = Flip(e1.V2(),e1) ( == e)4 -> 5;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 5
      outward normal = 1 -0

  Edges:   No. 1 : (0 0.5,0.5 0.5),  No. 2 : (0.5 0.5,0.5 1),  No. 3 : (0.5 1,0 1),  No. 4 : (0 1,0 0.5), 
Cell 3 has volume 0.25; 4  Vertices:  3 6 7 4  and 2 Nbs': 
    4 :[ Edge(*c,*nb) : 7 -> 4;  Edge(*nb,*c) : 4 -> 7;  Edge(nb) : 7 -> 4]
CyclicPred(nb) : 1 CyclicSucc(nb) : 1 v1: 7 v2: 4 
e   =                         7 -> 4
e1  = Flip(v1,e):             6 -> 7;  e2  = Flip(v2,e):             4 -> 3
e12 = Flip(e1.V2(),e1) ( == e)7 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)7 -> 4
      outward normal = 0 1
    1 :[ Edge(*c,*nb) : 4 -> 3;  Edge(*nb,*c) : 3 -> 4;  Edge(nb) : 4 -> 3]
CyclicPred(nb) : 4 CyclicSucc(nb) : 4 v1: 4 v2: 3 
e   =                         4 -> 3
e1  = Flip(v1,e):             7 -> 4;  e2  = Flip(v2,e):             3 -> 6
e12 = Flip(e1.V2(),e1) ( == e)4 -> 3;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 3
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0,1 0),  No. 2 : (1 0,1 0.5),  No. 3 : (1 0.5,0.5 0.5),  No. 4 : (0.5 0.5,0.5 0), 
Cell 4 has volume 0.25; 4  Vertices:  4 7 8 5  and 2 Nbs': 
    3 :[ Edge(*c,*nb) : 4 -> 7;  Edge(*nb,*c) : 7 -> 4;  Edge(nb) : 4 -> 7]
CyclicPred(nb) : 2 CyclicSucc(nb) : 2 v1: 4 v2: 7 
e   =                         4 -> 7
e1  = Flip(v1,e):             5 -> 4;  e2  = Flip(v2,e):             7 -> 8
e12 = Flip(e1.V2(),e1) ( == e)4 -> 7;  e21 = Flip(e2.V1(),e2) ( == e)4 -> 7
      outward normal = 0 -1
    2 :[ Edge(*c,*nb) : 5 -> 4;  Edge(*nb,*c) : 4 -> 5;  Edge(nb) : 5 -> 4]
CyclicPred(nb) : 3 CyclicSucc(nb) : 3 v1: 5 v2: 4 
e   =                         5 -> 4
e1  = Flip(v1,e):             8 -> 5;  e2  = Flip(v2,e):             4 -> 7
e12 = Flip(e1.V2(),e1) ( == e)5 -> 4;  e21 = Flip(e2.V1(),e2) ( == e)5 -> 4
      outward normal = -1 -0

  Edges:   No. 1 : (0.5 0.5,1 0.5),  No. 2 : (1 0.5,1 1),  No. 3 : (1 1,0.5 1),  No. 4 : (0.5 1,0.5 0.5), 
Edge [0 <-> 3]    [0 0 <-> 0.5 0]  adj. cells: 1,-1   volume = 0.5 normal = -0 1
Edge [1 <-> 0]    [0 0.5 <-> 0 0]  adj. cells: 1,-1   volume = 0.5 normal = 1 0
Edge [1 <-> 4]    [0 0.5 <-> 0.5 0.5]  adj. cells: 2,1   volume = 0.5 normal = -0 1
Edge [5 <-> 2]    [0.5 1 <-> 0 1]  adj. cells: 2,-1   volume = 0.5 normal = -0 -1
Edge [2 <-> 1]    [0 1 <-> 0 0.5]  adj. cells: 2,-1   volume = 0.5 normal = 1 0
Edge [3 <-> 6]    [0.5 0 <-> 1 0]  adj. cells: 3,-1   volume = 0.5 normal = -0 1
Edge [6 <-> 7]    [1 0 <-> 1 0.5]  adj. cells: 3,-1   volume = 0.5 normal = -1 0
Edge [4 <-> 3]    [0.5 0.5 <-> 0.5 0]  adj. cells: 3,1   volume = 0.5 normal = 1 0
Edge [4 <-> 7]    [0.5 0.5 <-> 1 0.5]  adj. cells: 4,3   volume = 0.5 normal = -0 1
Edge [7 <-> 8]    [1 0.5 <-> 1 1]  adj. cells: 4,-1   volume = 0.5 normal = -1 0
Edge [8 <-> 5]    [1 1 <-> 0.5 1]  adj. cells: 4,-1   volume = 0.5 normal = -0 -1
Edge [5 <-> 4]    [0.5 1 <-> 0.5 0.5]  adj. cells: 4,2   volume = 0.5 normal = 1 0

Boundary-Edges: 
Edge (0 0.5,0 0)
Edge (0 0,0.5 0)
Edge (0 1,0 0.5)
Edge (0.5 1,0 1)
Edge (0.5 0,1 0)
Edge (1 1,0.5 1)
Edge (1 0,1 0.5)
Edge (1 0.5,1 1)

-----------------------------------------------------------
                       boundary
-----------------------------------------------------------

Boundary-Edges:
# 0  (V1,V2) =  (1,0)  coords =  (0 0.5,0 0)
# 1  (V1,V2) =  (0,3)  coords =  (0 0,0.5 0)
# 2  (V1,V2) =  (3,6)  coords =  (0.5 0,1 0)
# 3  (V1,V2) =  (6,7)  coords =  (1 0,1 0.5)
# 4  (V1,V2) =  (7,8)  coords =  (1 0.5,1 1)
# 5  (V1,V2) =  (8,5)  coords =  (1 1,0.5 1)
# 6  (V1,V2) =  (5,2)  coords =  (0.5 1,0 1)
# 7  (V1,V2) =  (2,1)  coords =  (0 1,0 0.5)


Boundary Vertices:
# 0  VNum = 0  coord = 0 0
# 1  VNum = 3  coord = 0.5 0
# 2  VNum = 6  coord = 1 0
# 3  VNum = 7  coord = 1 0.5
# 4  VNum = 8  coord = 1 1
# 5  VNum = 5  coord = 0.5 1
# 6  VNum = 2  coord = 0 1
# 7  VNum = 1  coord = 0 0.5

---------------------------------------------------
---------------------------------------------------

Testing CC[3]
0 vertices,  0 cells.

Boundary-Edges: 

-----------------------------------------------------------
                       boundary
-----------------------------------------------------------

Boundary-Edges:


Boundary Vertices:

---------------------------------------------------
---------------------------------------------------

