#!/bin/csh
./test-construct |& sed -e '/nan/s//NaN/g' >& out.out
/bin/echo "\n"
foreach i ( out.out case*.grid.out )
diff $i `basename $i .out`.exp
if ($status) then 
/bin/echo "\t\t\t" ERROR in $i
else
/bin/echo "\t\t\t" $i OK
endif
end
/bin/echo "\n"

