#!/bin/sh
./test-construct 2>&1 | sed -e '/nan/s//NaN/g' > out.out
/bin/echo "\n"
for i in out.out case*.grid.out 
do
if diff $i `basename $i .out`.exp
then
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done
/bin/echo "\n"

