Dimension: 2  c1.NumOfCells()=1  c1.NumOfFaces()=1 c1.NumOfEdges()=4 c1.NumOfVertices()=4
Dimension: 1  e1.NumOfCells()=1  e1.NumOfEdges()=1 e1.NumOfVertices()=2
Dimension: 0  v1.NumOfCells()=1  v1.NumOfVertices()=1
Dimension: 3  c1.NumOfCells()=1  c1.NumOfFaces()=6 c1.NumOfEdges()=12 c1.NumOfVertices()=8
Dimension: 2  f1.NumOfCells()=1  f1.NumOfFaces()=1 f1.NumOfEdges()=4 f1.NumOfVertices()=4
Dimension: 1  e1.NumOfCells()=1  e1.NumOfEdges()=1 e1.NumOfVertices()=2
Dimension: 0  v1.NumOfCells()=1  v1.NumOfVertices()=1
