Bucket grid: [0 0 @ 0 0,1 1 @ 1 1]
Bucket histogram:
1 cells: 1 buckets.
Buckets:
bucket 0 0: 0 0, 
0 0: in cell 0 0
-1 0:  projected to 0 0 in  cell 0 0
1 1:  projected to 1 1 in  cell 0 0
0.5 0.5: in cell 0 0
1 0:  projected to 1 0 in  cell 0 0
0 1:  projected to 0 1 in  cell 0 0
V(0,0) @0 0
V(5,5) @-5 5
Bucket grid: [0 0 @ -5 0,5 5 @ 0 5]
Bucket histogram:
1 cells: 25 buckets.
Buckets:
bucket 0 0: 0 4, 
bucket 0 1: 1 4, 
bucket 0 2: 2 4, 
bucket 0 3: 3 4, 
bucket 0 4: 4 4, 
bucket 1 0: 0 3, 
bucket 1 1: 1 3, 
bucket 1 2: 2 3, 
bucket 1 3: 3 3, 
bucket 1 4: 4 3, 
bucket 2 0: 0 2, 
bucket 2 1: 1 2, 
bucket 2 2: 2 2, 
bucket 2 3: 3 2, 
bucket 2 4: 4 2, 
bucket 3 0: 0 1, 
bucket 3 1: 1 1, 
bucket 3 2: 2 1, 
bucket 3 3: 3 1, 
bucket 3 4: 4 1, 
bucket 4 0: 0 0, 
bucket 4 1: 1 0, 
bucket 4 2: 2 0, 
bucket 4 3: 3 0, 
bucket 4 4: 4 0, 
0 0:  projected to 0 0 in  cell 0 0
-1 0: in cell 0 0
1 1:  projected to 0 1 in  cell 0 0
0 0.5:  projected to 0 0.5 in  cell 0 0
0 1:  projected to 0 1 in  cell 0 0
0 5:  projected to 0 5 in  cell 4 0
-0.5 4.5: in cell 4 0
-4.5 4.5: in cell 4 4
-4.5 0.5: in cell 0 4
-0.5 5.5:  projected to -0.5 5 in  cell 4 0
-5.5 5.5:  projected to -5 5 in  cell 4 4
-5.5 0.5:  projected to -5 0.5 in  cell 0 4
Bucket grid: [0 0 @ -10 0,10 10 @ 10 20]
Bucket histogram:
2 cells: 20 buckets.
4 cells: 40 buckets.
Buckets:




bucket 0 4: 0 8, 0 9, 
bucket 0 5: 0 9, 1 9, 







bucket 1 3: 0 6, 0 7, 
bucket 1 4: 0 7, 1 7, 0 8, 1 8, 
bucket 1 5: 1 8, 2 8, 1 9, 2 9, 
bucket 1 6: 2 9, 3 9, 





bucket 2 2: 0 4, 0 5, 
bucket 2 3: 0 5, 1 5, 0 6, 1 6, 
bucket 2 4: 1 6, 2 6, 1 7, 2 7, 
bucket 2 5: 2 7, 3 7, 2 8, 3 8, 
bucket 2 6: 3 8, 4 8, 3 9, 4 9, 
bucket 2 7: 4 9, 5 9, 



bucket 3 1: 0 2, 0 3, 
bucket 3 2: 0 3, 0 4, 1 3, 1 4, 
bucket 3 3: 1 4, 1 5, 2 4, 2 5, 
bucket 3 4: 2 5, 2 6, 3 5, 3 6, 
bucket 3 5: 3 6, 3 7, 4 6, 4 7, 
bucket 3 6: 4 7, 4 8, 5 7, 5 8, 
bucket 3 7: 5 8, 5 9, 6 8, 6 9, 
bucket 3 8: 6 9, 7 9, 

bucket 4 0: 0 0, 0 1, 
bucket 4 1: 0 1, 0 2, 1 1, 1 2, 
bucket 4 2: 1 2, 1 3, 2 2, 2 3, 
bucket 4 3: 2 3, 2 4, 3 3, 3 4, 
bucket 4 4: 3 4, 3 5, 4 4, 4 5, 
bucket 4 5: 4 5, 4 6, 5 5, 5 6, 
bucket 4 6: 5 6, 5 7, 6 6, 6 7, 
bucket 4 7: 6 7, 6 8, 7 7, 7 8, 
bucket 4 8: 7 8, 7 9, 8 8, 8 9, 
bucket 4 9: 8 9, 9 9, 
bucket 5 0: 0 0, 1 0, 
bucket 5 1: 1 0, 1 1, 2 0, 2 1, 
bucket 5 2: 2 1, 2 2, 3 1, 3 2, 
bucket 5 3: 3 2, 3 3, 4 2, 4 3, 
bucket 5 4: 4 3, 4 4, 5 3, 5 4, 
bucket 5 5: 5 4, 5 5, 6 4, 6 5, 
bucket 5 6: 6 5, 6 6, 7 5, 7 6, 
bucket 5 7: 7 6, 7 7, 8 6, 8 7, 
bucket 5 8: 8 7, 8 8, 9 7, 9 8, 
bucket 5 9: 9 8, 9 9, 

bucket 6 1: 2 0, 3 0, 
bucket 6 2: 3 0, 4 0, 3 1, 4 1, 
bucket 6 3: 4 1, 5 1, 4 2, 5 2, 
bucket 6 4: 5 2, 6 2, 5 3, 6 3, 
bucket 6 5: 6 3, 7 3, 6 4, 7 4, 
bucket 6 6: 7 4, 8 4, 7 5, 8 5, 
bucket 6 7: 8 5, 9 5, 8 6, 9 6, 
bucket 6 8: 9 6, 9 7, 



bucket 7 2: 4 0, 5 0, 
bucket 7 3: 5 0, 5 1, 6 0, 6 1, 
bucket 7 4: 6 1, 6 2, 7 1, 7 2, 
bucket 7 5: 7 2, 7 3, 8 2, 8 3, 
bucket 7 6: 8 3, 8 4, 9 3, 9 4, 
bucket 7 7: 9 4, 9 5, 





bucket 8 3: 6 0, 7 0, 
bucket 8 4: 7 0, 7 1, 8 0, 8 1, 
bucket 8 5: 8 1, 8 2, 9 1, 9 2, 
bucket 8 6: 9 2, 9 3, 







bucket 9 4: 8 0, 9 0, 
bucket 9 5: 9 0, 9 1, 




0 0: in cell 0 0
-1 0:  projected to 0 0 in  cell 0 0
1 1: in cell 0 0
0 0.5: in cell 0 0
0 1: in cell 0 0
0 5: in cell 2 2
-0.5 9.5: in cell 4 4
-9.5 9.5: in cell 0 9
-9.5 0.5:  not found in grid
V(0 0) @ 0 0
V(5 5) @ 15 15
Bucket grid: [0 0 @ 0 0,5 5 @ 15 15]
Bucket histogram:
1 cells: 2 buckets.
2 cells: 4 buckets.
3 cells: 2 buckets.
5 cells: 4 buckets.
7 cells: 3 buckets.
Buckets:
bucket 0 0: 0 0, 0 1, 1 0, 
bucket 0 1: 0 1, 0 2, 



bucket 1 0: 1 0, 2 0, 
bucket 1 1: 0 2, 1 1, 2 0, 0 1, 1 0, 1 2, 2 1, 
bucket 1 2: 0 3, 1 2, 0 2, 0 4, 1 3, 
bucket 1 3: 0 4, 


bucket 2 1: 2 1, 3 0, 2 0, 3 1, 4 0, 
bucket 2 2: 1 3, 2 2, 3 1, 1 2, 2 1, 2 3, 3 2, 
bucket 2 3: 1 4, 2 3, 0 4, 1 3, 2 4, 


bucket 3 1: 4 0, 
bucket 3 2: 3 2, 4 1, 3 1, 4 0, 4 2, 
bucket 3 3: 2 4, 3 3, 4 2, 2 3, 3 2, 3 4, 4 3, 
bucket 3 4: 3 4, 2 4, 



bucket 4 3: 4 3, 4 2, 
bucket 4 4: 4 4, 3 4, 4 3, 
0 0: in cell 0 0
15 15:  projected to 15 15 in  cell 4 4
5 10: in cell 0 4
10 5: in cell 4 0
1 0:  projected to 0 0 in  cell 0 0
0 1:  projected to 0 0 in  cell 0 0
-1 -1:  projected to 0 0 in  cell 0 0
20 30:  projected to 15 15 in  cell 4 4
2 1: in cell 0 0
2 0:  projected to 2 1 in  cell 0 0
3 0:  projected to 2 1 in  cell 0 0
4 0:  projected to 4 2 in  cell 1 0
5 0:  projected to 4 2 in  cell 1 0
2 -1:  projected to 2 1 in  cell 0 0
3 -1:  projected to 2 1 in  cell 0 0
4 -1:  projected to 4 2 in  cell 1 0
5 -1:  projected to 4 2 in  cell 1 0
