Number of levels: 1
Splitting cell 0 0 => active range on level 1 is: 0 0, 0 1, 1 0, 1 1, 
Splitting cell 0 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 
Splitting cell 1 0 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 3 0, 3 1, 
Splitting cell 1 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Number of levels: 2
Joining cell 0 0 => active range on level 1 is: 0 2, 0 3, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 0 1 => active range on level 1 is: 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 1 0 => active range on level 1 is: 2 2, 2 3, 3 2, 3 3, 
Joining cell 1 1 => active range on level 1 is: 
Number of levels: 1
Number of levels: 2
Joining cell 0 0 => active range on level 0 is: 
Number of levels: 1
