Octree state: Number of levels: 1 ( 0 .. 0 )
              Number of cells:  0
              Number of leafs:  0
Splitting cell 0 0 => active range on level 1 is: 0 0, 0 1, 1 0, 1 1, 
Splitting cell 0 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 
Splitting cell 1 0 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 3 0, 3 1, 
Splitting cell 1 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Octree state: Number of levels: 2 ( 0 .. 1 )
              Number of cells:  20
              Number of leafs:  16
Joining cell 0 0 => active range on level 1 is: 0 2, 0 3, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 0 1 => active range on level 1 is: 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 1 0 => active range on level 1 is: 2 2, 2 3, 3 2, 3 3, 
Joining cell 1 1 => active range on level 1 is: 
Octree state: Number of levels: 1 ( 0 .. 0 )
              Number of cells:  4
              Number of leafs:  4
Number of levels: 2
Joining cell 0 0 => active range on level 0 is: 
Octree state: Number of levels: 1 ( -1 .. -1 )
              Number of cells:  1
              Number of leafs:  1
Leafs:
0 0
