Octree state: Number of levels: 1 ( 0 .. 0 )
              Number of cells:  4
              Number of leafs:  4
Splitting cell 0 0 => active range on level 1 is: 0 0, 0 1, 1 0, 1 1, 
Splitting cell 0 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 
Splitting cell 1 0 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 3 0, 3 1, 
Splitting cell 1 1 => active range on level 1 is: 0 0, 0 1, 0 2, 0 3, 1 0, 1 1, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Octree state: Number of levels: 2 ( 0 .. 1 )
              Number of cells:  20
              Number of leafs:  16
Joining cell 0 0 => active range on level 1 is: 0 2, 0 3, 1 2, 1 3, 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 0 1 => active range on level 1 is: 2 0, 2 1, 2 2, 2 3, 3 0, 3 1, 3 2, 3 3, 
Joining cell 1 0 => active range on level 1 is: 2 2, 2 3, 3 2, 3 3, 
Joining cell 1 1 => active range on level 1 is: 
Octree state: Number of levels: 1 ( 0 .. 0 )
              Number of cells:  4
              Number of leafs:  4
Number of levels: 2
Joining cell 0 0 => active range on level 0 is: 
Octree state: Number of levels: 1 ( -1 .. -1 )
              Number of cells:  1
              Number of leafs:  1
Leafs:
0 0
refine towards:
Octree state: Number of levels: 2 ( 0 .. 1 )
              Number of cells:  1
              Number of leafs:  1
Octree state: Number of levels: 2 ( 0 .. 1 )
              Number of cells:  5
              Number of leafs:  4
Level 0:
Cell 0 0
Level 1:
Cell 0 0 (L)
Cell 0 1 (L)
Cell 1 0 (L)
Cell 1 1 (L)
Octree state: Number of levels: 4 ( 0 .. 3 )
              Number of cells:  13
              Number of leafs:  10
Level 0:
Cell 0 0
Level 1:
Cell 0 0 (L)
Cell 0 1 (L)
Cell 1 0 (L)
Cell 1 1
Level 2:
Cell 2 2
Cell 2 3 (L)
Cell 3 2 (L)
Cell 3 3 (L)
Level 3:
Cell 4 4 (L)
Cell 4 5 (L)
Cell 5 4 (L)
Cell 5 5 (L)
balancing:
Octree state: Number of levels: 4 ( 0 .. 3 )
              Number of cells:  21
              Number of leafs:  16
Level 0:
Cell 0 0
Level 1:
Cell 0 0 (L)
Cell 0 1
Cell 1 0
Cell 1 1
Level 2:
Cell 0 2 (L)
Cell 0 3 (L)
Cell 1 2 (L)
Cell 1 3 (L)
Cell 2 0 (L)
Cell 2 1 (L)
Cell 2 2
Cell 2 3 (L)
Cell 3 0 (L)
Cell 3 1 (L)
Cell 3 2 (L)
Cell 3 3 (L)
Level 3:
Cell 4 4 (L)
Cell 4 5 (L)
Cell 5 4 (L)
Cell 5 5 (L)
