#!/bin/sh
./test-bijective  > out 2>&1
for i in  out 
do
/bin/echo "\n"
if diff -w $i $i.exp
then 
/bin/echo "\t\t\t" $i OK
status=0
else
/bin/echo "\t\t\t" ERROR in $i
status=1
fi
done
/bin/echo "\n"
exit $status
