has    type vertex_handle
has    type edge_handle
has no type face_handle
has    type facet_handle
has    type cell_handle
has    type Vertex
has    type Edge
has no type Face
has    type Facet
has    type Cell
has    type VertexIterator
has    type EdgeIterator
has no type FaceIterator
has    type FacetIterator
has    type CellIterator
has no type VertexOnVertexIterator
has    type EdgeOnVertexIterator
has no type FaceOnVertexIterator
has no type FacetOnVertexIterator
has    type CellOnVertexIterator
has    type VertexOnEdgeIterator
has no type FaceOnEdgeIterator
has no type FacetOnEdgeIterator
has no type CellOnEdgeIterator
has no type VertexOnFaceIterator
has no type EdgeOnFaceIterator
has no type CellOnFaceIterator
has no type VertexOnFacetIterator
has no type EdgeOnFacetIterator
has    type CellOnFacetIterator
has    type VertexOnCellIterator
has no type EdgeOnCellIterator
has no type FaceOnCellIterator
has    type FacetOnCellIterator
has no type CellOnCellIterator
has    type archetype_type
has    type archetype_handle
has    type archetype_iterator
  ->  (v=0 c=0)   ->  (v=1 c=0)   ->  (v=1 c=1)   ->  (v=2 c=1)   ->  (v=2 c=2)   ->  (v=0 c=2) 
