
PWD=$(shell pwd)
CONFIG=$(PWD)/../mk.config

SUBDIRS = boundary-grid  \
          cell-on-cell-iterator \
          cell-on-vertex-iterator \
          connected-components \
          construct-isomorphism  \
          disjoint-union \
          edge-iterator-of-cell-set \
          element-grid \
          element-range \
          enumerated-subrange \
          extend-grid-types \
          extrusion-view \
          facet-iterator-of-cell-set \
          flag \
          geometric-types \
          grid-as-volume \
          incidence-hulls \
          multi-grid-function \
          partial-grid-morphism \
          polygon1d \
          restricted-component-view \
          shrunk-grid-view \
          vertex-iterator-of-cell-set  \
          vertex-stars 




include  $(CONFIG)
include  $(RECURSIVETARGETS)




