
PWD=$(shell pwd)
CONFIG=$(PWD)/../mk.config

SUBDIRS = archetype0D \
          boundary-grid  \
          boundary-range-nd \
          cell-as-volume \
          cell-on-cell-iterator \
          cell-on-vertex-iterator \
          closure-iterator \
          collapsed-grid-view \
          connected-components \
          construct-isomorphism  \
          disjoint-union \
          edge-iterator-of-cell-set \
          element-grid \
          element-numbering \
          element-range \
          enumerated-subrange \
          extend-grid-types \
          extrusion-view \
          facet-iterator-of-cell-set \
          flag \
          geometric-types \
          grid-as-volume \
          grid-function-array-adapter \
          grid-types \
          incident \
          incidence-hulls \
          mapped-grid-function \
          morphisms \
          multi-grid-function \
          partial-grid-morphism \
          polygon1d \
          restricted-component-view \
	  restricted-grid-view \
          shrunk-grid-view \
          simple-geometry \
          single-element-iterator \
          stream-grid-adapter \
          vertex-iterator-of-cell-set  \
          vertex-on-vertex-iterator \
          vertex-stars \
          wrap-elements




include  $(CONFIG)
include  $(RECURSIVETARGETS)




