# generic Makefile for Obj directories

include $(CONFIG)

# sources are in parent directory
VPATH=..
OBJ  = $(SRC:%.C=%.o)
DEPS = $(SRC:%.C=%.d)

include $(DEPS)

CCFLAGS += $(LIBCCFLAGS)

new: clean all

all: compile lib

compile: $(OBJ)

lib: $(OBJ)
	mkdir -p $(LIBDIR)
	$(AR) $(ARFLGS) $(LIBDIR)/$(LIB) $(?);

clean: stdclean
	rm -f *.o  *.a *~ *.flc core .depend *.d
	rm -rf tempinc

