Testing T
4 vertices,  2 cells.
Vertex 0
Vertex 1
Vertex 2
Vertex 3
Cell 0 has 3  Vertices:  0 1 2 
  Neighbors -1 -1 1 
  Edges:   No. 0 : (0,1),  No. 1 : (1,2),  No. 2 : (2,0), 
Cell 1 has 3  Vertices:  0 2 3 
  Neighbors 0 -1 -1 
  Edges:   No. 0 : (0,2),  No. 1 : (2,3),  No. 2 : (3,0), 
---------------------------------------------------
---------------------------------------------------



Cell Neighbors
-1 -1 1 
0 -1 -1 
