#!/bin/sh

out=out

if ! ./test-triang2d-construct -f grid.complex2d > $out 2>&1
then
    echo "ERROR running test-triang2d-construct
Output was:
"
cat $out
echo "
End output
"
else
/bin/echo "\n"
for i in out 
do
if ! diff $i $i.exp
then
/bin/echo "\t\t\t" ERROR in $i
else
/bin/echo "\t\t\t" $i OK
fi
done
/bin/echo "\n"
fi
