Testing T
4 vertices,  2 cells.
Vertex 0
Vertex 1
Vertex 2
Vertex 3
Cell 0 has 3  Vertices:  0 1 2 
  Neighbors -1 -1 1 
  Edges:   No. 0 : (0,1),  No. 1 : (1,2),  No. 2 : (2,0), 
Cell 1 has 3  Vertices:  0 2 3 
  Neighbors 0 -1 -1 
  Edges:   No. 0 : (0,2),  No. 1 : (2,3),  No. 2 : (3,0), 
---------------------------------------------------
---------------------------------------------------



Cell Neighbors
-1 -1 1 
0 -1 -1 
Testing the switch operators:
fc = 0 0 Nb: -1
  switch_vertex(0,0 0) = 1
  switch_facet(0,0 0,0) = 0 2
  switch_vertex(1,0 0) = 0
  switch_facet(1,0 0,0) = 0 1
fc = 0 1 Nb: -1
  switch_vertex(1,0 1) = 2
  switch_facet(1,0 1,0) = 0 0
  switch_vertex(2,0 1) = 1
  switch_facet(2,0 1,0) = 0 2
fc = 0 2 Nb: 1
  switch_vertex(2,0 2) = 0
  switch_facet(2,0 2,0) = 0 1
  switch_facet(2,0 2,1) = 1 1
  switch_vertex(0,0 2) = 2
  switch_facet(0,0 2,0) = 0 0
  switch_facet(0,0 2,1) = 1 2
fc = 1 0 Nb: 0
  switch_vertex(0,1 0) = 2
  switch_facet(0,1 0,1) = 1 2
  switch_facet(0,1 0,0) = 0 0
  switch_vertex(2,1 0) = 0
  switch_facet(2,1 0,1) = 1 1
  switch_facet(2,1 0,0) = 0 1
fc = 1 1 Nb: -1
  switch_vertex(2,1 1) = 3
  switch_facet(2,1 1,1) = 1 0
  switch_vertex(3,1 1) = 2
  switch_facet(3,1 1,1) = 1 2
fc = 1 2 Nb: -1
  switch_vertex(3,1 2) = 0
  switch_facet(3,1 2,1) = 1 1
  switch_vertex(0,1 2) = 3
  switch_facet(0,1 2,1) = 1 0
