Point 0 0 is     inside finite,      inside infinite
Point 0 2 is     inside finite,      inside infinite
Point 0 1 is     inside finite,      inside infinite
Point 0 -0.5 is not inside finite,      inside infinite
Point 0 2.5 is not inside finite,      inside infinite
Point 0.4 1 is     inside finite,      inside infinite
Point 0.6 1 is not inside finite,  not inside infinite
Segment s = [0 0,1 0]
Point 0 0: s.project(p) = 0; s.nearest(p) = 0 0; distance(p,s) = 0
Point 1 0: s.project(p) = 1; s.nearest(p) = 1 0; distance(p,s) = 0
Point 0.5 0: s.project(p) = 0.5; s.nearest(p) = 0.5 0; distance(p,s) = 0
Point 0.5 1: s.project(p) = 0.5; s.nearest(p) = 0.5 0; distance(p,s) = 1
Point -2 0: s.project(p) = -2; s.nearest(p) = 0 0; distance(p,s) = 2
Point -4 3: s.project(p) = -4; s.nearest(p) = 0 0; distance(p,s) = 5
Point 0 1: s.project(p) = 0; s.nearest(p) = 0 0; distance(p,s) = 1
Point 1 1: s.project(p) = 1; s.nearest(p) = 1 0; distance(p,s) = 1
Point 2 0: s.project(p) = 2; s.nearest(p) = 1 0; distance(p,s) = 1
Point 5 3: s.project(p) = 5; s.nearest(p) = 1 0; distance(p,s) = 5
