Cell 0 has 2 neighbors 
Contents of nbs:  -1  2  1  -1 
With generic iterator #1: [2] [1] 
With generic iterator #2: [2] [1] 
With generic iterator #2 (all facets): [-1]b [2]i [1]i [-1]b 
With native  iterator:    [2] [1] 
Cell 1 has 2 neighbors 
Contents of nbs:  0  3  -1  -1 
With generic iterator #1: [0] [3] 
With generic iterator #2: [0] [3] 
With generic iterator #2 (all facets): [0]i [3]i [-1]b [-1]b 
With native  iterator:    [0] [3] 
Cell 2 has 2 neighbors 
Contents of nbs:  -1  -1  3  0 
With generic iterator #1: [3] [0] 
With generic iterator #2: [3] [0] 
With generic iterator #2 (all facets): [-1]b [-1]b [3]i [0]i 
With native  iterator:    [3] [0] 
Cell 3 has 2 neighbors 
Contents of nbs:  2  -1  -1  1 
With generic iterator #1: [2] [1] 
With generic iterator #2: [2] [1] 
With generic iterator #2 (all facets): [2]i [-1]b [-1]b [1]i 
With native  iterator:    [2] [1] 
