#!/bin/bash

out=out

if ! ./test-boundary-grids > $out 2>&1
then
    echo "ERROR running test-boundary-grids
Output was:
"
cat $out
echo "
End output
"
else
/bin/echo "\n"
for i in  out
do
if diff $i $i.exp
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done
/bin/echo "\n"
fi
