Grid 1:
V @ 0 0 is     inside
V @ 0 1 is     inside
V @ 0 2 is  not inside
V @ 0 3 is  not inside
V @ 0 4 is  not inside
V @ 1 0 is     inside
V @ 1 1 is     inside
V @ 1 2 is  not inside
V @ 1 3 is  not inside
V @ 1 4 is  not inside
V @ 2 0 is  not inside
V @ 2 1 is  not inside
V @ 2 2 is  not inside
V @ 2 3 is  not inside
V @ 2 4 is  not inside
V @ 3 0 is  not inside
V @ 3 1 is  not inside
V @ 3 2 is  not inside
V @ 3 3 is  not inside
V @ 3 4 is  not inside
V @ 4 0 is  not inside
V @ 4 1 is  not inside
V @ 4 2 is  not inside
V @ 4 3 is  not inside
V @ 4 4 is  not inside
C 0 0: intersections
C 0 1: intersections
C 0 2: outside
C 0 3: outside
C 1 0: intersections
C 1 1: intersections
C 1 2: outside
C 1 3: outside
C 2 0: outside
C 2 1: outside
C 2 2: outside
C 2 3: outside
C 3 0: outside
C 3 1: outside
C 3 2: outside
C 3 3: outside
Grid 2:
V @ 0 0 is     inside
V @ 0 0.125 is     inside
V @ 0 0.25 is     inside
V @ 0.125 0 is     inside
V @ 0.125 0.125 is     inside
V @ 0.125 0.25 is     inside
V @ 0.25 0 is     inside
V @ 0.25 0.125 is     inside
V @ 0.25 0.25 is     inside
C2 0 0: intersections
C2 0 1: intersections
C2 1 0: intersections
C2 1 1: intersections
