export CONFIG:=$(shell pwd)/mk.config
unexport PWD
include $(CONFIG)



install-headers: std-install-headers

new: libclean

all:

test:

check:

demo:

test-check-clean:

clean: stdclean

realclean: clean
	rm -rf doxygen

ADDRELPATH=..
