-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 3 = 3 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 2 = 2 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 3 = 3 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 3 = 3 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 2 = 2 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 3 = 3 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
