-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 3 = 3 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 2 = 2 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 3 = 3 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 3 = 3 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 2 = 2 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 3 = 3 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
2 2


2   0 1 
2   1 0 
master -> part (vertices):
part 0
0 -> 0
1 -> 3
2 -> 5
3 -> 1
4 -> 2
5 -> 4
6 -> 6
7 -> 7
8 -> 8
part 1
0 -> 8
1 -> 6
2 -> 7
3 -> 0
4 -> 3
5 -> 5
6 -> 1
7 -> 2
8 -> 4

9 4

0 0
0.5 0
0.5 0.5
0 0.5
0.5 1
0 1
1 0
1 0.5
1 1

4   0 1 2 3 
4   3 2 4 5 
4   1 6 7 2 
4   2 7 8 4 

9 4

0.5 0
1 0
1 0.5
0.5 0.5
1 1
0.5 1
0 0.5
0 1
0 0

4   0 1 2 3 
4   3 2 4 5 
4   6 3 5 7 
4   8 0 3 6 

