-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 3 = 3 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 2 = 2 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 3 = 3 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 3 = 3 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 2 = 2 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 3 = 3 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
2 2


2   0 1 
2   1 0 
master -> part (vertices):
part 0
0 -> 0
1 -> 3
2 -> 5
3 -> 1
4 -> 2
5 -> 4
6 -> 6
7 -> 7
8 -> 8
9 -> 9
10 -> 10
11 -> 11
part 1
3 -> 11
4 -> 9
5 -> 10
6 -> 0
7 -> 3
8 -> 5
9 -> 1
10 -> 2
11 -> 4
12 -> 6
13 -> 7
14 -> 8

12 6

0 0
1 0
1 1
0 1
1 2
0 2
2 0
2 1
2 2
3 0
3 1
3 2

4   0 1 2 3 
4   3 2 4 5 
4   1 6 7 2 
4   2 7 8 4 
4   6 9 10 7 
4   7 10 11 8 

12 6

2 0
3 0
3 1
2 1
3 2
2 2
4 0
4 1
4 2
1 1
1 2
1 0

4   0 1 2 3 
4   3 2 4 5 
4   1 6 7 2 
4   2 7 8 4 
4   9 3 5 10 
4   11 0 3 9 

-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 3 = 3 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 2 = 2 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 3 = 3 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 3 = 3 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 2 = 2 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 3 = 3 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
2 2


2   0 1 
2   1 0 
master -> part (vertices):
part 0
0 -> 0
1 -> 3
2 -> 5
3 -> 1
4 -> 2
5 -> 4
6 -> 6
7 -> 7
8 -> 8
9 -> 9
10 -> 10
11 -> 11
part 1
3 -> 11
4 -> 9
5 -> 10
6 -> 0
7 -> 3
8 -> 5
9 -> 1
10 -> 2
11 -> 4
12 -> 6
13 -> 7
14 -> 8

12 6

0 0
1 0
1 1
0 1
1 2
0 2
2 0
2 1
2 2
3 0
3 1
3 2

4   0 1 2 3 
4   3 2 4 5 
4   1 6 7 2 
4   2 7 8 4 
4   6 9 10 7 
4   7 10 11 8 

12 6

2 0
3 0
3 1
2 1
3 2
2 2
4 0
4 1
4 2
1 1
1 2
1 0

4   0 1 2 3 
4   3 2 4 5 
4   1 6 7 2 
4   2 7 8 4 
4   9 3 5 10 
4   11 0 3 9 

-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 3 = 3 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 2 = 2 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 3 = 3 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 3 = 3 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 2 = 2 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 3 = 3 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
