-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 2 = 2 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 1 = 1 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 2 = 2 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 0 = 0 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 0 = 0 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 2 = 2 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
4 2


2   0 1 
2   2 3 
master -> part (vertices):
part 0
0 -> 0
1 -> 2
2 -> 1
3 -> 3
4 -> 4
5 -> 5
part 1
2 -> 6
3 -> 7
4 -> 0
5 -> 3
6 -> 1
7 -> 2
8 -> 4
9 -> 5

6 2

0 0
1 0
0 1
1 1
2 0
2 1

4   0 1 2 3 
4   1 4 5 3 

8 3

2 0
3 0
3 1
2 1
4 0
4 1
1 0
1 1

4   0 1 2 3 
4   1 4 5 2 
4   6 0 3 7 

