-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 2 = 2 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 1 = 1 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 2 = 2 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 2 = 2 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 1 = 1 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 2 = 2 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
2 2


2   0 1 
2   1 0 
master -> part (vertices):
part 0
0 -> 0
1 -> 3
2 -> 1
3 -> 2
4 -> 4
5 -> 5
6 -> 6
7 -> 7
part 1
2 -> 6
3 -> 7
4 -> 0
5 -> 3
6 -> 1
7 -> 2
8 -> 4
9 -> 5

8 3

0 0
1 0
1 1
0 1
2 0
2 1
3 0
3 1

4  0 1 2 3 
4  1 4 5 2 
4  4 6 7 5 

8 3

2 0
3 0
3 1
2 1
4 0
4 1
1 0
1 1

4  0 1 2 3 
4  1 4 5 2 
4  6 0 3 7 

-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 2 = 2 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 1 = 1 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 2 = 2 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 2 = 2 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 1 = 1 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 2 = 2 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
2 2


2   0 1 
2   1 0 
master -> part (vertices):
part 0
0 -> 0
1 -> 3
2 -> 1
3 -> 2
4 -> 4
5 -> 5
6 -> 6
7 -> 7
part 1
2 -> 6
3 -> 7
4 -> 0
5 -> 3
6 -> 1
7 -> 2
8 -> 4
9 -> 5

8 3

0 0
1 0
1 1
0 1
2 0
2 1
3 0
3 1

4  0 1 2 3 
4  1 4 5 2 
4  4 6 7 5 

8 3

2 0
3 0
3 1
2 1
4 0
4 1
1 0
1 1

4  0 1 2 3 
4  1 4 5 2 
4  6 0 3 7 

-------------------------------------------------
checking cell 0

   |CopiedVertices(1,0)| = 2 = 2 = |ExposedVertices(0,1)|
   |CopiedCells(1,0)| = 1 = 1 = |ExposedCells(0,1)|
   |SharedVertices(1,0)| = 2 = 2 = |SharedVertices(0,1)|
   |SharedCells(1,0)| = 0 = 0 = |SharedCells(0,1)|
-------------------------------------------------
-------------------------------------------------
checking cell 1

   |CopiedVertices(0,1)| = 2 = 2 = |ExposedVertices(1,0)|
   |CopiedCells(0,1)| = 1 = 1 = |ExposedCells(1,0)|
   |SharedVertices(0,1)| = 2 = 2 = |SharedVertices(1,0)|
   |SharedCells(0,1)| = 0 = 0 = |SharedCells(1,0)|
-------------------------------------------------
