#!/bin/bash
rm -f grid.complex2d grid.part
cp    grid2x2.complex2d grid.complex2d
cp    grid2x2.part.2    grid.part
./test-composite  > out2x2 2>&1
rm -f grid.complex2d grid.part
cp    grid4x1.complex2d grid.complex2d
cp    grid4x1.part.2    grid.part
./test-composite  > out4x1 2>&1
rm -f grid.complex2d grid.part
cp    grid2x2.complex2d grid.complex2d
cp    grid2x2.part.1    grid.part
./test-composite  > out2x2p1 2>&1
rm -f grid.complex2d grid.part
cp    grid4x1.complex2d grid.complex2d
cp    grid4x1.part.1    grid.part
./test-composite  > out4x1p1 2>&1


/bin/echo "\n"
for i in out2x2 out4x1 out2x2p1 out4x1p1
do
if diff $i $i.exp
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done
/bin/echo "\n"

