#!/bin/bash

out=out4x2p2
mkdir -p compgrid-out
rm -f grid.complex2d grid.part $out
cp    grid4x2.complex2d grid.complex2d
cp    grid4x2.part.2    grid.part

if ! ./test-composite  > $out 2>&1
then
echo "ERROR running test-composite for 4x2, 2 partitions
Output was:
"
cat $out
echo "
End output
"
else
/bin/echo "\n"
for i in  $out
do
if diff $i $i.exp
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done

for i in  `ls compgrid-out/compgrid.*`
do
c=`echo $i | perl -p -e "s/compgrid-out/compgrid-out.exp/g"`
ib=`echo $i | perl -p -e "s/compgrid\./compgridB\./g"`
if diff $i  $c
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
if diff $ib  $c
then 
/bin/echo "\t\t\t" $ib OK
else
/bin/echo "\t\t\t" ERROR in $ib
fi
done


/bin/echo "\n"
fi
