#!/bin/bash

out=out4x2p2
rm -f grid.complex2d grid.part $out
cp    grid4x2.complex2d grid.complex2d
cp    grid4x2.part.2    grid.part

if ! ./test-composite  > $out 2>&1
then
echo "ERROR running test-composite for 4x2, 2 partitions
Output was:
"
cat $out
echo "
End output
"
else
/bin/echo "\n"
for i in  $out
do
if diff $i $i.exp
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done

for i in  compgrid.*
do
if diff $i compgrid-out.exp/$i
then 
/bin/echo "\t\t\t" $i OK
else
/bin/echo "\t\t\t" ERROR in $i
fi
done


/bin/echo "\n"
fi
