ComplexND<3> incidences:
Anchor dimension: 0
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
  Value dimension: 3
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
  Value dimension: 3
  --------------------------
=================================
Anchor dimension: 2
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
  Value dimension: 3
  --------------------------
=================================
Anchor dimension: 3
  Value dimension: 0
    0: 8 incidences of dim 0: 0 1 2 3 4 5 6 7 
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
  Value dimension: 3
  --------------------------
=================================
ComplexND<2> incidences:
Anchor dimension: 0
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
Anchor dimension: 2
  Value dimension: 0
    0: 4 incidences of dim 0: 0 3 4 1 
    1: 4 incidences of dim 0: 1 4 5 2 
    2: 4 incidences of dim 0: 3 6 7 4 
    3: 4 incidences of dim 0: 4 7 8 5 
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
ComplexND<1> triangle incidences:
Anchor dimension: 0
  Value dimension: 0
    0: 2 incidences of dim 0: 1 2 
    1: 2 incidences of dim 0: 0 2 
    2: 2 incidences of dim 0: 1 0 
  --------------------------
  Value dimension: 1
    0: 2 incidences of dim 1: 0 2 
    1: 2 incidences of dim 1: 0 1 
    2: 2 incidences of dim 1: 1 2 
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
    0: 2 incidences of dim 0: 0 1 
    1: 2 incidences of dim 0: 1 2 
    2: 2 incidences of dim 0: 2 0 
  --------------------------
  Value dimension: 1
    0: 2 incidences of dim 1: 2 1 
    1: 2 incidences of dim 1: 0 2 
    2: 2 incidences of dim 1: 1 0 
  --------------------------
=================================
ComplexND<1> single edge incidences:
Anchor dimension: 0
  Value dimension: 0
    0: 1 incidences of dim 0: 1 
    1: 1 incidences of dim 0: 0 
  --------------------------
  Value dimension: 1
    0: 1 incidences of dim 1: 0 
    1: 1 incidences of dim 1: 0 
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
    0: 2 incidences of dim 0: 0 1 
  --------------------------
  Value dimension: 1
    0: 2 incidences of dim 1: -1 -1 
  --------------------------
=================================
ComplexND<ANY> incidences:
Anchor dimension: 0
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
Anchor dimension: 2
  Value dimension: 0
    0: 4 incidences of dim 0: 0 3 4 1 
    1: 4 incidences of dim 0: 1 4 5 2 
    2: 4 incidences of dim 0: 3 6 7 4 
    3: 4 incidences of dim 0: 4 7 8 5 
  --------------------------
  Value dimension: 1
  --------------------------
  Value dimension: 2
  --------------------------
=================================
Incidences of polygon1:
Anchor dimension: 0
  Value dimension: 0
    0: 2 incidences of dim 0: 4 1 
    1: 2 incidences of dim 0: 0 2 
    2: 2 incidences of dim 0: 1 3 
    3: 2 incidences of dim 0: 2 4 
    4: 2 incidences of dim 0: 3 0 
  --------------------------
  Value dimension: 1
    0: 2 incidences of dim 1: 0 4 
    1: 2 incidences of dim 1: 1 0 
    2: 2 incidences of dim 1: 2 1 
    3: 2 incidences of dim 1: 3 2 
    4: 2 incidences of dim 1: 4 3 
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
    0: 2 incidences of dim 0: 0 1 
    1: 2 incidences of dim 0: 1 2 
    2: 2 incidences of dim 0: 2 3 
    3: 2 incidences of dim 0: 3 4 
    4: 2 incidences of dim 0: 4 0 
  --------------------------
  Value dimension: 1
    0: 2 incidences of dim 1: 4 1 
    1: 2 incidences of dim 1: 0 2 
    2: 2 incidences of dim 1: 1 3 
    3: 2 incidences of dim 1: 2 4 
    4: 2 incidences of dim 1: 3 0 
  --------------------------
=================================
Incidences of polygon2:
Anchor dimension: 0
  Value dimension: 0
  --------------------------
  Value dimension: 1
  --------------------------
=================================
Anchor dimension: 1
  Value dimension: 0
    0: 2 incidences of dim 0: 0 1 
    1: 2 incidences of dim 0: 1 2 
    2: 2 incidences of dim 0: 2 3 
    3: 2 incidences of dim 0: 3 4 
    4: 2 incidences of dim 0: 4 0 
  --------------------------
  Value dimension: 1
  --------------------------
=================================
