Level -1: 1 1 1  cells
Level 0: 2 2 2  cells
Level 1: 4 4 4  cells
child: 0 0 0 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 0 0 1 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 0 0 2 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 0 0 3 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 0 1 0 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 0 1 1 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 0 1 2 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 0 1 3 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 0 2 0 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 0 2 1 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 0 2 2 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 0 2 3 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 0 3 0 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 0 3 1 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 0 3 2 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 0 3 3 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 1 0 0 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 1 0 1 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 1 0 2 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 1 0 3 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 1 1 0 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 1 1 1 ; parent: 0 0 0 ; (children: 0 0 0 , 0 0 1 , 0 1 0 , 0 1 1 , 1 0 0 , 1 0 1 , 1 1 0 , 1 1 1 , ) grandp: 0 0 0 
child: 1 1 2 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 1 1 3 ; parent: 0 0 1 ; (children: 0 0 2 , 0 0 3 , 0 1 2 , 0 1 3 , 1 0 2 , 1 0 3 , 1 1 2 , 1 1 3 , ) grandp: 0 0 0 
child: 1 2 0 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 1 2 1 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 1 2 2 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 1 2 3 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 1 3 0 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 1 3 1 ; parent: 0 1 0 ; (children: 0 2 0 , 0 2 1 , 0 3 0 , 0 3 1 , 1 2 0 , 1 2 1 , 1 3 0 , 1 3 1 , ) grandp: 0 0 0 
child: 1 3 2 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 1 3 3 ; parent: 0 1 1 ; (children: 0 2 2 , 0 2 3 , 0 3 2 , 0 3 3 , 1 2 2 , 1 2 3 , 1 3 2 , 1 3 3 , ) grandp: 0 0 0 
child: 2 0 0 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 2 0 1 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 2 0 2 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 2 0 3 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 2 1 0 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 2 1 1 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 2 1 2 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 2 1 3 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 2 2 0 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 2 2 1 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 2 2 2 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 2 2 3 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 2 3 0 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 2 3 1 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 2 3 2 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 2 3 3 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 3 0 0 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 3 0 1 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 3 0 2 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 3 0 3 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 3 1 0 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 3 1 1 ; parent: 1 0 0 ; (children: 2 0 0 , 2 0 1 , 2 1 0 , 2 1 1 , 3 0 0 , 3 0 1 , 3 1 0 , 3 1 1 , ) grandp: 0 0 0 
child: 3 1 2 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 3 1 3 ; parent: 1 0 1 ; (children: 2 0 2 , 2 0 3 , 2 1 2 , 2 1 3 , 3 0 2 , 3 0 3 , 3 1 2 , 3 1 3 , ) grandp: 0 0 0 
child: 3 2 0 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 3 2 1 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 3 2 2 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 3 2 3 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 3 3 0 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 3 3 1 ; parent: 1 1 0 ; (children: 2 2 0 , 2 2 1 , 2 3 0 , 2 3 1 , 3 2 0 , 3 2 1 , 3 3 0 , 3 3 1 , ) grandp: 0 0 0 
child: 3 3 2 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
child: 3 3 3 ; parent: 1 1 1 ; (children: 2 2 2 , 2 2 3 , 2 3 2 , 2 3 3 , 3 2 2 , 3 2 3 , 3 3 2 , 3 3 3 , ) grandp: 0 0 0 
----------------------------
Level -1: 1 1  cells
Level 0: 3 3  cells
Level 1: 9 9  cells
child: 0 0 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 0 1 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 0 2 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 0 3 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 0 4 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 0 5 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 0 6 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 0 7 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 0 8 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 1 0 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 1 1 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 1 2 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 1 3 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 1 4 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 1 5 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 1 6 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 1 7 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 1 8 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 2 0 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 2 1 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 2 2 ; parent: 0 0 ; (children: 0 0 , 0 1 , 0 2 , 1 0 , 1 1 , 1 2 , 2 0 , 2 1 , 2 2 , ) grandp: 0 0 
child: 2 3 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 2 4 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 2 5 ; parent: 0 1 ; (children: 0 3 , 0 4 , 0 5 , 1 3 , 1 4 , 1 5 , 2 3 , 2 4 , 2 5 , ) grandp: 0 0 
child: 2 6 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 2 7 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 2 8 ; parent: 0 2 ; (children: 0 6 , 0 7 , 0 8 , 1 6 , 1 7 , 1 8 , 2 6 , 2 7 , 2 8 , ) grandp: 0 0 
child: 3 0 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 3 1 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 3 2 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 3 3 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 3 4 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 3 5 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 3 6 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 3 7 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 3 8 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 4 0 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 4 1 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 4 2 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 4 3 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 4 4 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 4 5 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 4 6 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 4 7 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 4 8 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 5 0 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 5 1 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 5 2 ; parent: 1 0 ; (children: 3 0 , 3 1 , 3 2 , 4 0 , 4 1 , 4 2 , 5 0 , 5 1 , 5 2 , ) grandp: 0 0 
child: 5 3 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 5 4 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 5 5 ; parent: 1 1 ; (children: 3 3 , 3 4 , 3 5 , 4 3 , 4 4 , 4 5 , 5 3 , 5 4 , 5 5 , ) grandp: 0 0 
child: 5 6 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 5 7 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 5 8 ; parent: 1 2 ; (children: 3 6 , 3 7 , 3 8 , 4 6 , 4 7 , 4 8 , 5 6 , 5 7 , 5 8 , ) grandp: 0 0 
child: 6 0 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 6 1 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 6 2 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 6 3 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 6 4 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 6 5 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 6 6 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 6 7 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 6 8 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 7 0 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 7 1 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 7 2 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 7 3 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 7 4 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 7 5 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 7 6 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 7 7 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 7 8 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 8 0 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 8 1 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 8 2 ; parent: 2 0 ; (children: 6 0 , 6 1 , 6 2 , 7 0 , 7 1 , 7 2 , 8 0 , 8 1 , 8 2 , ) grandp: 0 0 
child: 8 3 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 8 4 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 8 5 ; parent: 2 1 ; (children: 6 3 , 6 4 , 6 5 , 7 3 , 7 4 , 7 5 , 8 3 , 8 4 , 8 5 , ) grandp: 0 0 
child: 8 6 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 8 7 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
child: 8 8 ; parent: 2 2 ; (children: 6 6 , 6 7 , 6 8 , 7 6 , 7 7 , 7 8 , 8 6 , 8 7 , 8 8 , ) grandp: 0 0 
