Level -1: 1 1 1 cells
Descendant of cell 0 0 0: 64 cells: [0 0 0,3 3 3]  125 vertices: [0 0 0,4 4 4]
Level 0: 2 2 2 cells
Descendant of cell 0 0 0: 8 cells: [0 0 0,1 1 1]  27 vertices: [0 0 0,2 2 2]
Descendant of cell 0 0 1: 8 cells: [0 0 2,1 1 3]  27 vertices: [0 0 2,2 2 4]
Descendant of cell 0 1 0: 8 cells: [0 2 0,1 3 1]  27 vertices: [0 2 0,2 4 2]
Descendant of cell 0 1 1: 8 cells: [0 2 2,1 3 3]  27 vertices: [0 2 2,2 4 4]
Descendant of cell 1 0 0: 8 cells: [2 0 0,3 1 1]  27 vertices: [2 0 0,4 2 2]
Descendant of cell 1 0 1: 8 cells: [2 0 2,3 1 3]  27 vertices: [2 0 2,4 2 4]
Descendant of cell 1 1 0: 8 cells: [2 2 0,3 3 1]  27 vertices: [2 2 0,4 4 2]
Descendant of cell 1 1 1: 8 cells: [2 2 2,3 3 3]  27 vertices: [2 2 2,4 4 4]
Level 1: 4 4 4 cells
Descendant of cell 0 0 0: 1 cells: [0 0 0,0 0 0]  8 vertices: [0 0 0,1 1 1]
Descendant of cell 0 0 1: 1 cells: [0 0 1,0 0 1]  8 vertices: [0 0 1,1 1 2]
Descendant of cell 0 0 2: 1 cells: [0 0 2,0 0 2]  8 vertices: [0 0 2,1 1 3]
Descendant of cell 0 0 3: 1 cells: [0 0 3,0 0 3]  8 vertices: [0 0 3,1 1 4]
Descendant of cell 0 1 0: 1 cells: [0 1 0,0 1 0]  8 vertices: [0 1 0,1 2 1]
Descendant of cell 0 1 1: 1 cells: [0 1 1,0 1 1]  8 vertices: [0 1 1,1 2 2]
Descendant of cell 0 1 2: 1 cells: [0 1 2,0 1 2]  8 vertices: [0 1 2,1 2 3]
Descendant of cell 0 1 3: 1 cells: [0 1 3,0 1 3]  8 vertices: [0 1 3,1 2 4]
Descendant of cell 0 2 0: 1 cells: [0 2 0,0 2 0]  8 vertices: [0 2 0,1 3 1]
Descendant of cell 0 2 1: 1 cells: [0 2 1,0 2 1]  8 vertices: [0 2 1,1 3 2]
Descendant of cell 0 2 2: 1 cells: [0 2 2,0 2 2]  8 vertices: [0 2 2,1 3 3]
Descendant of cell 0 2 3: 1 cells: [0 2 3,0 2 3]  8 vertices: [0 2 3,1 3 4]
Descendant of cell 0 3 0: 1 cells: [0 3 0,0 3 0]  8 vertices: [0 3 0,1 4 1]
Descendant of cell 0 3 1: 1 cells: [0 3 1,0 3 1]  8 vertices: [0 3 1,1 4 2]
Descendant of cell 0 3 2: 1 cells: [0 3 2,0 3 2]  8 vertices: [0 3 2,1 4 3]
Descendant of cell 0 3 3: 1 cells: [0 3 3,0 3 3]  8 vertices: [0 3 3,1 4 4]
Descendant of cell 1 0 0: 1 cells: [1 0 0,1 0 0]  8 vertices: [1 0 0,2 1 1]
Descendant of cell 1 0 1: 1 cells: [1 0 1,1 0 1]  8 vertices: [1 0 1,2 1 2]
Descendant of cell 1 0 2: 1 cells: [1 0 2,1 0 2]  8 vertices: [1 0 2,2 1 3]
Descendant of cell 1 0 3: 1 cells: [1 0 3,1 0 3]  8 vertices: [1 0 3,2 1 4]
Descendant of cell 1 1 0: 1 cells: [1 1 0,1 1 0]  8 vertices: [1 1 0,2 2 1]
Descendant of cell 1 1 1: 1 cells: [1 1 1,1 1 1]  8 vertices: [1 1 1,2 2 2]
Descendant of cell 1 1 2: 1 cells: [1 1 2,1 1 2]  8 vertices: [1 1 2,2 2 3]
Descendant of cell 1 1 3: 1 cells: [1 1 3,1 1 3]  8 vertices: [1 1 3,2 2 4]
Descendant of cell 1 2 0: 1 cells: [1 2 0,1 2 0]  8 vertices: [1 2 0,2 3 1]
Descendant of cell 1 2 1: 1 cells: [1 2 1,1 2 1]  8 vertices: [1 2 1,2 3 2]
Descendant of cell 1 2 2: 1 cells: [1 2 2,1 2 2]  8 vertices: [1 2 2,2 3 3]
Descendant of cell 1 2 3: 1 cells: [1 2 3,1 2 3]  8 vertices: [1 2 3,2 3 4]
Descendant of cell 1 3 0: 1 cells: [1 3 0,1 3 0]  8 vertices: [1 3 0,2 4 1]
Descendant of cell 1 3 1: 1 cells: [1 3 1,1 3 1]  8 vertices: [1 3 1,2 4 2]
Descendant of cell 1 3 2: 1 cells: [1 3 2,1 3 2]  8 vertices: [1 3 2,2 4 3]
Descendant of cell 1 3 3: 1 cells: [1 3 3,1 3 3]  8 vertices: [1 3 3,2 4 4]
Descendant of cell 2 0 0: 1 cells: [2 0 0,2 0 0]  8 vertices: [2 0 0,3 1 1]
Descendant of cell 2 0 1: 1 cells: [2 0 1,2 0 1]  8 vertices: [2 0 1,3 1 2]
Descendant of cell 2 0 2: 1 cells: [2 0 2,2 0 2]  8 vertices: [2 0 2,3 1 3]
Descendant of cell 2 0 3: 1 cells: [2 0 3,2 0 3]  8 vertices: [2 0 3,3 1 4]
Descendant of cell 2 1 0: 1 cells: [2 1 0,2 1 0]  8 vertices: [2 1 0,3 2 1]
Descendant of cell 2 1 1: 1 cells: [2 1 1,2 1 1]  8 vertices: [2 1 1,3 2 2]
Descendant of cell 2 1 2: 1 cells: [2 1 2,2 1 2]  8 vertices: [2 1 2,3 2 3]
Descendant of cell 2 1 3: 1 cells: [2 1 3,2 1 3]  8 vertices: [2 1 3,3 2 4]
Descendant of cell 2 2 0: 1 cells: [2 2 0,2 2 0]  8 vertices: [2 2 0,3 3 1]
Descendant of cell 2 2 1: 1 cells: [2 2 1,2 2 1]  8 vertices: [2 2 1,3 3 2]
Descendant of cell 2 2 2: 1 cells: [2 2 2,2 2 2]  8 vertices: [2 2 2,3 3 3]
Descendant of cell 2 2 3: 1 cells: [2 2 3,2 2 3]  8 vertices: [2 2 3,3 3 4]
Descendant of cell 2 3 0: 1 cells: [2 3 0,2 3 0]  8 vertices: [2 3 0,3 4 1]
Descendant of cell 2 3 1: 1 cells: [2 3 1,2 3 1]  8 vertices: [2 3 1,3 4 2]
Descendant of cell 2 3 2: 1 cells: [2 3 2,2 3 2]  8 vertices: [2 3 2,3 4 3]
Descendant of cell 2 3 3: 1 cells: [2 3 3,2 3 3]  8 vertices: [2 3 3,3 4 4]
Descendant of cell 3 0 0: 1 cells: [3 0 0,3 0 0]  8 vertices: [3 0 0,4 1 1]
Descendant of cell 3 0 1: 1 cells: [3 0 1,3 0 1]  8 vertices: [3 0 1,4 1 2]
Descendant of cell 3 0 2: 1 cells: [3 0 2,3 0 2]  8 vertices: [3 0 2,4 1 3]
Descendant of cell 3 0 3: 1 cells: [3 0 3,3 0 3]  8 vertices: [3 0 3,4 1 4]
Descendant of cell 3 1 0: 1 cells: [3 1 0,3 1 0]  8 vertices: [3 1 0,4 2 1]
Descendant of cell 3 1 1: 1 cells: [3 1 1,3 1 1]  8 vertices: [3 1 1,4 2 2]
Descendant of cell 3 1 2: 1 cells: [3 1 2,3 1 2]  8 vertices: [3 1 2,4 2 3]
Descendant of cell 3 1 3: 1 cells: [3 1 3,3 1 3]  8 vertices: [3 1 3,4 2 4]
Descendant of cell 3 2 0: 1 cells: [3 2 0,3 2 0]  8 vertices: [3 2 0,4 3 1]
Descendant of cell 3 2 1: 1 cells: [3 2 1,3 2 1]  8 vertices: [3 2 1,4 3 2]
Descendant of cell 3 2 2: 1 cells: [3 2 2,3 2 2]  8 vertices: [3 2 2,4 3 3]
Descendant of cell 3 2 3: 1 cells: [3 2 3,3 2 3]  8 vertices: [3 2 3,4 3 4]
Descendant of cell 3 3 0: 1 cells: [3 3 0,3 3 0]  8 vertices: [3 3 0,4 4 1]
Descendant of cell 3 3 1: 1 cells: [3 3 1,3 3 1]  8 vertices: [3 3 1,4 4 2]
Descendant of cell 3 3 2: 1 cells: [3 3 2,3 3 2]  8 vertices: [3 3 2,4 4 3]
Descendant of cell 3 3 3: 1 cells: [3 3 3,3 3 3]  8 vertices: [3 3 3,4 4 4]
child: 0 0 0; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 0 0 1; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 0 0 2; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 0 0 3; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 0 1 0; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 0 1 1; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 0 1 2; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 0 1 3; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 0 2 0; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 0 2 1; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 0 2 2; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 0 2 3; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 0 3 0; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 0 3 1; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 0 3 2; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 0 3 3; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 1 0 0; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 1 0 1; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 1 0 2; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 1 0 3; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 1 1 0; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 1 1 1; parent: 0 0 0; (children: 0 0 0, 0 0 1, 0 1 0, 0 1 1, 1 0 0, 1 0 1, 1 1 0, 1 1 1, ) grandp: 0 0 0
child: 1 1 2; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 1 1 3; parent: 0 0 1; (children: 0 0 2, 0 0 3, 0 1 2, 0 1 3, 1 0 2, 1 0 3, 1 1 2, 1 1 3, ) grandp: 0 0 0
child: 1 2 0; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 1 2 1; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 1 2 2; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 1 2 3; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 1 3 0; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 1 3 1; parent: 0 1 0; (children: 0 2 0, 0 2 1, 0 3 0, 0 3 1, 1 2 0, 1 2 1, 1 3 0, 1 3 1, ) grandp: 0 0 0
child: 1 3 2; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 1 3 3; parent: 0 1 1; (children: 0 2 2, 0 2 3, 0 3 2, 0 3 3, 1 2 2, 1 2 3, 1 3 2, 1 3 3, ) grandp: 0 0 0
child: 2 0 0; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 2 0 1; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 2 0 2; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 2 0 3; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 2 1 0; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 2 1 1; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 2 1 2; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 2 1 3; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 2 2 0; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 2 2 1; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 2 2 2; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 2 2 3; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 2 3 0; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 2 3 1; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 2 3 2; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 2 3 3; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 3 0 0; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 3 0 1; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 3 0 2; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 3 0 3; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 3 1 0; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 3 1 1; parent: 1 0 0; (children: 2 0 0, 2 0 1, 2 1 0, 2 1 1, 3 0 0, 3 0 1, 3 1 0, 3 1 1, ) grandp: 0 0 0
child: 3 1 2; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 3 1 3; parent: 1 0 1; (children: 2 0 2, 2 0 3, 2 1 2, 2 1 3, 3 0 2, 3 0 3, 3 1 2, 3 1 3, ) grandp: 0 0 0
child: 3 2 0; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 3 2 1; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 3 2 2; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 3 2 3; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 3 3 0; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 3 3 1; parent: 1 1 0; (children: 2 2 0, 2 2 1, 2 3 0, 2 3 1, 3 2 0, 3 2 1, 3 3 0, 3 3 1, ) grandp: 0 0 0
child: 3 3 2; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0
child: 3 3 3; parent: 1 1 1; (children: 2 2 2, 2 2 3, 2 3 2, 2 3 3, 3 2 2, 3 2 3, 3 3 2, 3 3 3, ) grandp: 0 0 0

Vertices & Coarsest Parents:
0 0 0 -> 0 0 0, level -1
0 0 1 -> 0 0 1, level 1
0 0 2 -> 0 0 1, level 0
0 0 3 -> 0 0 3, level 1
0 0 4 -> 0 0 1, level -1
0 1 0 -> 0 1 0, level 1
0 1 1 -> 0 1 1, level 1
0 1 2 -> 0 1 2, level 1
0 1 3 -> 0 1 3, level 1
0 1 4 -> 0 1 4, level 1
0 2 0 -> 0 1 0, level 0
0 2 1 -> 0 2 1, level 1
0 2 2 -> 0 1 1, level 0
0 2 3 -> 0 2 3, level 1
0 2 4 -> 0 1 2, level 0
0 3 0 -> 0 3 0, level 1
0 3 1 -> 0 3 1, level 1
0 3 2 -> 0 3 2, level 1
0 3 3 -> 0 3 3, level 1
0 3 4 -> 0 3 4, level 1
0 4 0 -> 0 1 0, level -1
0 4 1 -> 0 4 1, level 1
0 4 2 -> 0 2 1, level 0
0 4 3 -> 0 4 3, level 1
0 4 4 -> 0 1 1, level -1
1 0 0 -> 1 0 0, level 1
1 0 1 -> 1 0 1, level 1
1 0 2 -> 1 0 2, level 1
1 0 3 -> 1 0 3, level 1
1 0 4 -> 1 0 4, level 1
1 1 0 -> 1 1 0, level 1
1 1 1 -> 1 1 1, level 1
1 1 2 -> 1 1 2, level 1
1 1 3 -> 1 1 3, level 1
1 1 4 -> 1 1 4, level 1
1 2 0 -> 1 2 0, level 1
1 2 1 -> 1 2 1, level 1
1 2 2 -> 1 2 2, level 1
1 2 3 -> 1 2 3, level 1
1 2 4 -> 1 2 4, level 1
1 3 0 -> 1 3 0, level 1
1 3 1 -> 1 3 1, level 1
1 3 2 -> 1 3 2, level 1
1 3 3 -> 1 3 3, level 1
1 3 4 -> 1 3 4, level 1
1 4 0 -> 1 4 0, level 1
1 4 1 -> 1 4 1, level 1
1 4 2 -> 1 4 2, level 1
1 4 3 -> 1 4 3, level 1
1 4 4 -> 1 4 4, level 1
2 0 0 -> 1 0 0, level 0
2 0 1 -> 2 0 1, level 1
2 0 2 -> 1 0 1, level 0
2 0 3 -> 2 0 3, level 1
2 0 4 -> 1 0 2, level 0
2 1 0 -> 2 1 0, level 1
2 1 1 -> 2 1 1, level 1
2 1 2 -> 2 1 2, level 1
2 1 3 -> 2 1 3, level 1
2 1 4 -> 2 1 4, level 1
2 2 0 -> 1 1 0, level 0
2 2 1 -> 2 2 1, level 1
2 2 2 -> 1 1 1, level 0
2 2 3 -> 2 2 3, level 1
2 2 4 -> 1 1 2, level 0
2 3 0 -> 2 3 0, level 1
2 3 1 -> 2 3 1, level 1
2 3 2 -> 2 3 2, level 1
2 3 3 -> 2 3 3, level 1
2 3 4 -> 2 3 4, level 1
2 4 0 -> 1 2 0, level 0
2 4 1 -> 2 4 1, level 1
2 4 2 -> 1 2 1, level 0
2 4 3 -> 2 4 3, level 1
2 4 4 -> 1 2 2, level 0
3 0 0 -> 3 0 0, level 1
3 0 1 -> 3 0 1, level 1
3 0 2 -> 3 0 2, level 1
3 0 3 -> 3 0 3, level 1
3 0 4 -> 3 0 4, level 1
3 1 0 -> 3 1 0, level 1
3 1 1 -> 3 1 1, level 1
3 1 2 -> 3 1 2, level 1
3 1 3 -> 3 1 3, level 1
3 1 4 -> 3 1 4, level 1
3 2 0 -> 3 2 0, level 1
3 2 1 -> 3 2 1, level 1
3 2 2 -> 3 2 2, level 1
3 2 3 -> 3 2 3, level 1
3 2 4 -> 3 2 4, level 1
3 3 0 -> 3 3 0, level 1
3 3 1 -> 3 3 1, level 1
3 3 2 -> 3 3 2, level 1
3 3 3 -> 3 3 3, level 1
3 3 4 -> 3 3 4, level 1
3 4 0 -> 3 4 0, level 1
3 4 1 -> 3 4 1, level 1
3 4 2 -> 3 4 2, level 1
3 4 3 -> 3 4 3, level 1
3 4 4 -> 3 4 4, level 1
4 0 0 -> 1 0 0, level -1
4 0 1 -> 4 0 1, level 1
4 0 2 -> 2 0 1, level 0
4 0 3 -> 4 0 3, level 1
4 0 4 -> 1 0 1, level -1
4 1 0 -> 4 1 0, level 1
4 1 1 -> 4 1 1, level 1
4 1 2 -> 4 1 2, level 1
4 1 3 -> 4 1 3, level 1
4 1 4 -> 4 1 4, level 1
4 2 0 -> 2 1 0, level 0
4 2 1 -> 4 2 1, level 1
4 2 2 -> 2 1 1, level 0
4 2 3 -> 4 2 3, level 1
4 2 4 -> 2 1 2, level 0
4 3 0 -> 4 3 0, level 1
4 3 1 -> 4 3 1, level 1
4 3 2 -> 4 3 2, level 1
4 3 3 -> 4 3 3, level 1
4 3 4 -> 4 3 4, level 1
4 4 0 -> 1 1 0, level -1
4 4 1 -> 4 4 1, level 1
4 4 2 -> 2 2 1, level 0
4 4 3 -> 4 4 3, level 1
4 4 4 -> 1 1 1, level -1
# levels: 2
# levels: 1
# levels: 0

GRAL_ERROR in FILE /usr/people/lnx10/berti/CVS-work/gral/hierarchical/include/Gral/Hierarchical/hierarchical-grid.h
      FUNCTION ce, LINE 239
      precondition violated: (!empty()) 
 Continuing. 
# levels: 0
----------------------------
Level -1: 1 1 cells
Descendant of cell 0 0: 100 cells: [0 0,9 9]  121 vertices: [0 0,10 10]
Level 0: 3 3 cells
Descendant of cell 0 0: 16 cells: [0 0,3 3]  25 vertices: [0 0,4 4]
Descendant of cell 0 1: 16 cells: [0 3,3 6]  25 vertices: [0 3,4 7]
Descendant of cell 0 2: 16 cells: [0 6,3 9]  25 vertices: [0 6,4 10]
Descendant of cell 1 0: 16 cells: [3 0,6 3]  25 vertices: [3 0,7 4]
Descendant of cell 1 1: 16 cells: [3 3,6 6]  25 vertices: [3 3,7 7]
Descendant of cell 1 2: 16 cells: [3 6,6 9]  25 vertices: [3 6,7 10]
Descendant of cell 2 0: 16 cells: [6 0,9 3]  25 vertices: [6 0,10 4]
Descendant of cell 2 1: 16 cells: [6 3,9 6]  25 vertices: [6 3,10 7]
Descendant of cell 2 2: 16 cells: [6 6,9 9]  25 vertices: [6 6,10 10]
Level 1: 9 9 cells
Descendant of cell 0 0: 4 cells: [0 0,1 1]  9 vertices: [0 0,2 2]
Descendant of cell 0 1: 4 cells: [0 1,1 2]  9 vertices: [0 1,2 3]
Descendant of cell 0 2: 4 cells: [0 2,1 3]  9 vertices: [0 2,2 4]
Descendant of cell 0 3: 4 cells: [0 3,1 4]  9 vertices: [0 3,2 5]
Descendant of cell 0 4: 4 cells: [0 4,1 5]  9 vertices: [0 4,2 6]
Descendant of cell 0 5: 4 cells: [0 5,1 6]  9 vertices: [0 5,2 7]
Descendant of cell 0 6: 4 cells: [0 6,1 7]  9 vertices: [0 6,2 8]
Descendant of cell 0 7: 4 cells: [0 7,1 8]  9 vertices: [0 7,2 9]
Descendant of cell 0 8: 4 cells: [0 8,1 9]  9 vertices: [0 8,2 10]
Descendant of cell 1 0: 4 cells: [1 0,2 1]  9 vertices: [1 0,3 2]
Descendant of cell 1 1: 4 cells: [1 1,2 2]  9 vertices: [1 1,3 3]
Descendant of cell 1 2: 4 cells: [1 2,2 3]  9 vertices: [1 2,3 4]
Descendant of cell 1 3: 4 cells: [1 3,2 4]  9 vertices: [1 3,3 5]
Descendant of cell 1 4: 4 cells: [1 4,2 5]  9 vertices: [1 4,3 6]
Descendant of cell 1 5: 4 cells: [1 5,2 6]  9 vertices: [1 5,3 7]
Descendant of cell 1 6: 4 cells: [1 6,2 7]  9 vertices: [1 6,3 8]
Descendant of cell 1 7: 4 cells: [1 7,2 8]  9 vertices: [1 7,3 9]
Descendant of cell 1 8: 4 cells: [1 8,2 9]  9 vertices: [1 8,3 10]
Descendant of cell 2 0: 4 cells: [2 0,3 1]  9 vertices: [2 0,4 2]
Descendant of cell 2 1: 4 cells: [2 1,3 2]  9 vertices: [2 1,4 3]
Descendant of cell 2 2: 4 cells: [2 2,3 3]  9 vertices: [2 2,4 4]
Descendant of cell 2 3: 4 cells: [2 3,3 4]  9 vertices: [2 3,4 5]
Descendant of cell 2 4: 4 cells: [2 4,3 5]  9 vertices: [2 4,4 6]
Descendant of cell 2 5: 4 cells: [2 5,3 6]  9 vertices: [2 5,4 7]
Descendant of cell 2 6: 4 cells: [2 6,3 7]  9 vertices: [2 6,4 8]
Descendant of cell 2 7: 4 cells: [2 7,3 8]  9 vertices: [2 7,4 9]
Descendant of cell 2 8: 4 cells: [2 8,3 9]  9 vertices: [2 8,4 10]
Descendant of cell 3 0: 4 cells: [3 0,4 1]  9 vertices: [3 0,5 2]
Descendant of cell 3 1: 4 cells: [3 1,4 2]  9 vertices: [3 1,5 3]
Descendant of cell 3 2: 4 cells: [3 2,4 3]  9 vertices: [3 2,5 4]
Descendant of cell 3 3: 4 cells: [3 3,4 4]  9 vertices: [3 3,5 5]
Descendant of cell 3 4: 4 cells: [3 4,4 5]  9 vertices: [3 4,5 6]
Descendant of cell 3 5: 4 cells: [3 5,4 6]  9 vertices: [3 5,5 7]
Descendant of cell 3 6: 4 cells: [3 6,4 7]  9 vertices: [3 6,5 8]
Descendant of cell 3 7: 4 cells: [3 7,4 8]  9 vertices: [3 7,5 9]
Descendant of cell 3 8: 4 cells: [3 8,4 9]  9 vertices: [3 8,5 10]
Descendant of cell 4 0: 4 cells: [4 0,5 1]  9 vertices: [4 0,6 2]
Descendant of cell 4 1: 4 cells: [4 1,5 2]  9 vertices: [4 1,6 3]
Descendant of cell 4 2: 4 cells: [4 2,5 3]  9 vertices: [4 2,6 4]
Descendant of cell 4 3: 4 cells: [4 3,5 4]  9 vertices: [4 3,6 5]
Descendant of cell 4 4: 4 cells: [4 4,5 5]  9 vertices: [4 4,6 6]
Descendant of cell 4 5: 4 cells: [4 5,5 6]  9 vertices: [4 5,6 7]
Descendant of cell 4 6: 4 cells: [4 6,5 7]  9 vertices: [4 6,6 8]
Descendant of cell 4 7: 4 cells: [4 7,5 8]  9 vertices: [4 7,6 9]
Descendant of cell 4 8: 4 cells: [4 8,5 9]  9 vertices: [4 8,6 10]
Descendant of cell 5 0: 4 cells: [5 0,6 1]  9 vertices: [5 0,7 2]
Descendant of cell 5 1: 4 cells: [5 1,6 2]  9 vertices: [5 1,7 3]
Descendant of cell 5 2: 4 cells: [5 2,6 3]  9 vertices: [5 2,7 4]
Descendant of cell 5 3: 4 cells: [5 3,6 4]  9 vertices: [5 3,7 5]
Descendant of cell 5 4: 4 cells: [5 4,6 5]  9 vertices: [5 4,7 6]
Descendant of cell 5 5: 4 cells: [5 5,6 6]  9 vertices: [5 5,7 7]
Descendant of cell 5 6: 4 cells: [5 6,6 7]  9 vertices: [5 6,7 8]
Descendant of cell 5 7: 4 cells: [5 7,6 8]  9 vertices: [5 7,7 9]
Descendant of cell 5 8: 4 cells: [5 8,6 9]  9 vertices: [5 8,7 10]
Descendant of cell 6 0: 4 cells: [6 0,7 1]  9 vertices: [6 0,8 2]
Descendant of cell 6 1: 4 cells: [6 1,7 2]  9 vertices: [6 1,8 3]
Descendant of cell 6 2: 4 cells: [6 2,7 3]  9 vertices: [6 2,8 4]
Descendant of cell 6 3: 4 cells: [6 3,7 4]  9 vertices: [6 3,8 5]
Descendant of cell 6 4: 4 cells: [6 4,7 5]  9 vertices: [6 4,8 6]
Descendant of cell 6 5: 4 cells: [6 5,7 6]  9 vertices: [6 5,8 7]
Descendant of cell 6 6: 4 cells: [6 6,7 7]  9 vertices: [6 6,8 8]
Descendant of cell 6 7: 4 cells: [6 7,7 8]  9 vertices: [6 7,8 9]
Descendant of cell 6 8: 4 cells: [6 8,7 9]  9 vertices: [6 8,8 10]
Descendant of cell 7 0: 4 cells: [7 0,8 1]  9 vertices: [7 0,9 2]
Descendant of cell 7 1: 4 cells: [7 1,8 2]  9 vertices: [7 1,9 3]
Descendant of cell 7 2: 4 cells: [7 2,8 3]  9 vertices: [7 2,9 4]
Descendant of cell 7 3: 4 cells: [7 3,8 4]  9 vertices: [7 3,9 5]
Descendant of cell 7 4: 4 cells: [7 4,8 5]  9 vertices: [7 4,9 6]
Descendant of cell 7 5: 4 cells: [7 5,8 6]  9 vertices: [7 5,9 7]
Descendant of cell 7 6: 4 cells: [7 6,8 7]  9 vertices: [7 6,9 8]
Descendant of cell 7 7: 4 cells: [7 7,8 8]  9 vertices: [7 7,9 9]
Descendant of cell 7 8: 4 cells: [7 8,8 9]  9 vertices: [7 8,9 10]
Descendant of cell 8 0: 4 cells: [8 0,9 1]  9 vertices: [8 0,10 2]
Descendant of cell 8 1: 4 cells: [8 1,9 2]  9 vertices: [8 1,10 3]
Descendant of cell 8 2: 4 cells: [8 2,9 3]  9 vertices: [8 2,10 4]
Descendant of cell 8 3: 4 cells: [8 3,9 4]  9 vertices: [8 3,10 5]
Descendant of cell 8 4: 4 cells: [8 4,9 5]  9 vertices: [8 4,10 6]
Descendant of cell 8 5: 4 cells: [8 5,9 6]  9 vertices: [8 5,10 7]
Descendant of cell 8 6: 4 cells: [8 6,9 7]  9 vertices: [8 6,10 8]
Descendant of cell 8 7: 4 cells: [8 7,9 8]  9 vertices: [8 7,10 9]
Descendant of cell 8 8: 4 cells: [8 8,9 9]  9 vertices: [8 8,10 10]
child: 0 0; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 0 1; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 0 2; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 0 3; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 0 4; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 0 5; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 0 6; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 0 7; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 0 8; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 1 0; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 1 1; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 1 2; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 1 3; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 1 4; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 1 5; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 1 6; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 1 7; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 1 8; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 2 0; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 2 1; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 2 2; parent: 0 0; (children: 0 0, 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2, ) grandp: 0 0
child: 2 3; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 2 4; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 2 5; parent: 0 1; (children: 0 3, 0 4, 0 5, 1 3, 1 4, 1 5, 2 3, 2 4, 2 5, ) grandp: 0 0
child: 2 6; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 2 7; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 2 8; parent: 0 2; (children: 0 6, 0 7, 0 8, 1 6, 1 7, 1 8, 2 6, 2 7, 2 8, ) grandp: 0 0
child: 3 0; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 3 1; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 3 2; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 3 3; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 3 4; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 3 5; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 3 6; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 3 7; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 3 8; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 4 0; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 4 1; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 4 2; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 4 3; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 4 4; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 4 5; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 4 6; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 4 7; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 4 8; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 5 0; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 5 1; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 5 2; parent: 1 0; (children: 3 0, 3 1, 3 2, 4 0, 4 1, 4 2, 5 0, 5 1, 5 2, ) grandp: 0 0
child: 5 3; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 5 4; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 5 5; parent: 1 1; (children: 3 3, 3 4, 3 5, 4 3, 4 4, 4 5, 5 3, 5 4, 5 5, ) grandp: 0 0
child: 5 6; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 5 7; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 5 8; parent: 1 2; (children: 3 6, 3 7, 3 8, 4 6, 4 7, 4 8, 5 6, 5 7, 5 8, ) grandp: 0 0
child: 6 0; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 6 1; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 6 2; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 6 3; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 6 4; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 6 5; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 6 6; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 6 7; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 6 8; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 7 0; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 7 1; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 7 2; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 7 3; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 7 4; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 7 5; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 7 6; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 7 7; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 7 8; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 8 0; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 8 1; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 8 2; parent: 2 0; (children: 6 0, 6 1, 6 2, 7 0, 7 1, 7 2, 8 0, 8 1, 8 2, ) grandp: 0 0
child: 8 3; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 8 4; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 8 5; parent: 2 1; (children: 6 3, 6 4, 6 5, 7 3, 7 4, 7 5, 8 3, 8 4, 8 5, ) grandp: 0 0
child: 8 6; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 8 7; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0
child: 8 8; parent: 2 2; (children: 6 6, 6 7, 6 8, 7 6, 7 7, 7 8, 8 6, 8 7, 8 8, ) grandp: 0 0

Vertices & Coarsest Parents:
0 0 -> 0 0, level -1
0 1 -> 0 1, level 1
0 2 -> 0 2, level 1
0 3 -> 0 1, level 0
0 4 -> 0 4, level 1
0 5 -> 0 5, level 1
0 6 -> 0 2, level 0
0 7 -> 0 7, level 1
0 8 -> 0 8, level 1
0 9 -> 0 1, level -1
1 0 -> 1 0, level 1
1 1 -> 1 1, level 1
1 2 -> 1 2, level 1
1 3 -> 1 3, level 1
1 4 -> 1 4, level 1
1 5 -> 1 5, level 1
1 6 -> 1 6, level 1
1 7 -> 1 7, level 1
1 8 -> 1 8, level 1
1 9 -> 1 9, level 1
2 0 -> 2 0, level 1
2 1 -> 2 1, level 1
2 2 -> 2 2, level 1
2 3 -> 2 3, level 1
2 4 -> 2 4, level 1
2 5 -> 2 5, level 1
2 6 -> 2 6, level 1
2 7 -> 2 7, level 1
2 8 -> 2 8, level 1
2 9 -> 2 9, level 1
3 0 -> 1 0, level 0
3 1 -> 3 1, level 1
3 2 -> 3 2, level 1
3 3 -> 1 1, level 0
3 4 -> 3 4, level 1
3 5 -> 3 5, level 1
3 6 -> 1 2, level 0
3 7 -> 3 7, level 1
3 8 -> 3 8, level 1
3 9 -> 1 3, level 0
4 0 -> 4 0, level 1
4 1 -> 4 1, level 1
4 2 -> 4 2, level 1
4 3 -> 4 3, level 1
4 4 -> 4 4, level 1
4 5 -> 4 5, level 1
4 6 -> 4 6, level 1
4 7 -> 4 7, level 1
4 8 -> 4 8, level 1
4 9 -> 4 9, level 1
5 0 -> 5 0, level 1
5 1 -> 5 1, level 1
5 2 -> 5 2, level 1
5 3 -> 5 3, level 1
5 4 -> 5 4, level 1
5 5 -> 5 5, level 1
5 6 -> 5 6, level 1
5 7 -> 5 7, level 1
5 8 -> 5 8, level 1
5 9 -> 5 9, level 1
6 0 -> 2 0, level 0
6 1 -> 6 1, level 1
6 2 -> 6 2, level 1
6 3 -> 2 1, level 0
6 4 -> 6 4, level 1
6 5 -> 6 5, level 1
6 6 -> 2 2, level 0
6 7 -> 6 7, level 1
6 8 -> 6 8, level 1
6 9 -> 2 3, level 0
7 0 -> 7 0, level 1
7 1 -> 7 1, level 1
7 2 -> 7 2, level 1
7 3 -> 7 3, level 1
7 4 -> 7 4, level 1
7 5 -> 7 5, level 1
7 6 -> 7 6, level 1
7 7 -> 7 7, level 1
7 8 -> 7 8, level 1
7 9 -> 7 9, level 1
8 0 -> 8 0, level 1
8 1 -> 8 1, level 1
8 2 -> 8 2, level 1
8 3 -> 8 3, level 1
8 4 -> 8 4, level 1
8 5 -> 8 5, level 1
8 6 -> 8 6, level 1
8 7 -> 8 7, level 1
8 8 -> 8 8, level 1
8 9 -> 8 9, level 1
9 0 -> 1 0, level -1
9 1 -> 9 1, level 1
9 2 -> 9 2, level 1
9 3 -> 3 1, level 0
9 4 -> 9 4, level 1
9 5 -> 9 5, level 1
9 6 -> 3 2, level 0
9 7 -> 9 7, level 1
9 8 -> 9 8, level 1
9 9 -> 1 1, level -1
# levels: 2
# levels: 1
# levels: 0

GRAL_ERROR in FILE /usr/people/lnx10/berti/CVS-work/gral/hierarchical/include/Gral/Hierarchical/hierarchical-grid.h
      FUNCTION ce, LINE 239
      precondition violated: (!empty()) 
 Continuing. 
# levels: 0
----------------------------
Level -1: 1 1 cells
Descendant of cell 0 0: 25 cells: [0 0,4 4]  36 vertices: [0 0,5 5]
Level 0: 2 2 cells
Descendant of cell 0 0: 9 cells: [0 0,2 2]  16 vertices: [0 0,3 3]
Descendant of cell 0 1: 9 cells: [0 2,2 4]  16 vertices: [0 2,3 5]
Descendant of cell 1 0: 9 cells: [2 0,4 2]  16 vertices: [2 0,5 3]
Descendant of cell 1 1: 9 cells: [2 2,4 4]  16 vertices: [2 2,5 5]
Level 1: 4 4 cells
Descendant of cell 0 0: 4 cells: [0 0,1 1]  9 vertices: [0 0,2 2]
Descendant of cell 0 1: 4 cells: [0 1,1 2]  9 vertices: [0 1,2 3]
Descendant of cell 0 2: 4 cells: [0 2,1 3]  9 vertices: [0 2,2 4]
Descendant of cell 0 3: 4 cells: [0 3,1 4]  9 vertices: [0 3,2 5]
Descendant of cell 1 0: 4 cells: [1 0,2 1]  9 vertices: [1 0,3 2]
Descendant of cell 1 1: 4 cells: [1 1,2 2]  9 vertices: [1 1,3 3]
Descendant of cell 1 2: 4 cells: [1 2,2 3]  9 vertices: [1 2,3 4]
Descendant of cell 1 3: 4 cells: [1 3,2 4]  9 vertices: [1 3,3 5]
Descendant of cell 2 0: 4 cells: [2 0,3 1]  9 vertices: [2 0,4 2]
Descendant of cell 2 1: 4 cells: [2 1,3 2]  9 vertices: [2 1,4 3]
Descendant of cell 2 2: 4 cells: [2 2,3 3]  9 vertices: [2 2,4 4]
Descendant of cell 2 3: 4 cells: [2 3,3 4]  9 vertices: [2 3,4 5]
Descendant of cell 3 0: 4 cells: [3 0,4 1]  9 vertices: [3 0,5 2]
Descendant of cell 3 1: 4 cells: [3 1,4 2]  9 vertices: [3 1,5 3]
Descendant of cell 3 2: 4 cells: [3 2,4 3]  9 vertices: [3 2,5 4]
Descendant of cell 3 3: 4 cells: [3 3,4 4]  9 vertices: [3 3,5 5]
child: 0 0; parent: 0 0; (children: 0 0, 0 1, 1 0, 1 1, ) grandp: 0 0
child: 0 1; parent: 0 0; (children: 0 0, 0 1, 1 0, 1 1, ) grandp: 0 0
child: 0 2; parent: 0 1; (children: 0 2, 0 3, 1 2, 1 3, ) grandp: 0 0
child: 0 3; parent: 0 1; (children: 0 2, 0 3, 1 2, 1 3, ) grandp: 0 0
child: 1 0; parent: 0 0; (children: 0 0, 0 1, 1 0, 1 1, ) grandp: 0 0
child: 1 1; parent: 0 0; (children: 0 0, 0 1, 1 0, 1 1, ) grandp: 0 0
child: 1 2; parent: 0 1; (children: 0 2, 0 3, 1 2, 1 3, ) grandp: 0 0
child: 1 3; parent: 0 1; (children: 0 2, 0 3, 1 2, 1 3, ) grandp: 0 0
child: 2 0; parent: 1 0; (children: 2 0, 2 1, 3 0, 3 1, ) grandp: 0 0
child: 2 1; parent: 1 0; (children: 2 0, 2 1, 3 0, 3 1, ) grandp: 0 0
child: 2 2; parent: 1 1; (children: 2 2, 2 3, 3 2, 3 3, ) grandp: 0 0
child: 2 3; parent: 1 1; (children: 2 2, 2 3, 3 2, 3 3, ) grandp: 0 0
child: 3 0; parent: 1 0; (children: 2 0, 2 1, 3 0, 3 1, ) grandp: 0 0
child: 3 1; parent: 1 0; (children: 2 0, 2 1, 3 0, 3 1, ) grandp: 0 0
child: 3 2; parent: 1 1; (children: 2 2, 2 3, 3 2, 3 3, ) grandp: 0 0
child: 3 3; parent: 1 1; (children: 2 2, 2 3, 3 2, 3 3, ) grandp: 0 0

Vertices & Coarsest Parents:
0 0 -> 0 0, level -1
0 1 -> 0 1, level 1
0 2 -> 0 1, level 0
0 3 -> 0 3, level 1
0 4 -> 0 1, level -1
1 0 -> 1 0, level 1
1 1 -> 1 1, level 1
1 2 -> 1 2, level 1
1 3 -> 1 3, level 1
1 4 -> 1 4, level 1
2 0 -> 1 0, level 0
2 1 -> 2 1, level 1
2 2 -> 1 1, level 0
2 3 -> 2 3, level 1
2 4 -> 1 2, level 0
3 0 -> 3 0, level 1
3 1 -> 3 1, level 1
3 2 -> 3 2, level 1
3 3 -> 3 3, level 1
3 4 -> 3 4, level 1
4 0 -> 1 0, level -1
4 1 -> 4 1, level 1
4 2 -> 2 1, level 0
4 3 -> 4 3, level 1
4 4 -> 1 1, level -1
# levels: 2
# levels: 1
# levels: 0

GRAL_ERROR in FILE /usr/people/lnx10/berti/CVS-work/gral/hierarchical/include/Gral/Hierarchical/hierarchical-grid.h
      FUNCTION ce, LINE 239
      precondition violated: (!empty()) 
 Continuing. 
# levels: 0
