PWD=$(shell pwd)
CONFIG=$(PWD)/../mk.config

SUBDIRS = affine-mapping \
          ap \
          array-operations \
          box \
          coordN \
          geometric-primitives \
          intersections \
          matrix \
          piecewise-linear-function \
          point-traits \
          simplex \
          vcg \


include  $(CONFIG)
include  $(RECURSIVETARGETS)



