PWD=$(shell pwd)
CONFIG=$(PWD)/../mk.config

SUBDIRS = affine-mapping \
          ap \
          box \
          coordN \
          intersections \
          matrix \
          simplex \


include  $(CONFIG)
include  $(RECURSIVETARGETS)



