Cell 0
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.5 0.5
  global: 0 0  local: 0 0  local->global: 0 0  jacobian: 1  f(x)=0 0
  global: 1 0  local: 1 0  local->global: 1 0  jacobian: 1  f(x)=1 0
  global: 1 1  local: 1 1  local->global: 1 1  jacobian: 1  f(x)=1 1
  global: 0 1  local: 0 1  local->global: 0 1  jacobian: 1  f(x)=0 1
Volume=integrate_global(1): 1
integrate_global(coord): 0.5 0.5
Center=    0.5 0.5
I(center)= 0.5 0.5
Cell 1
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 1.5 0.75
  global: 1 0  local: 0 0  local->global: 1 0  jacobian: 1  f(x)=1 0
  global: 2 0  local: 1 0  local->global: 2 0  jacobian: 2  f(x)=2 0
  global: 2 2  local: 1 1  local->global: 2 2  jacobian: 2  f(x)=2 2
  global: 1 1  local: 0 1  local->global: 1 1  jacobian: 1  f(x)=1 1
Volume=integrate_global(1): 1.5
integrate_global(coord): 2.25 1.125
Center=    1.5 0.75
I(center)= 1.5 0.75
Cell 2
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 3 1
  global: 2 0  local: 0 0  local->global: 2 0  jacobian: 4  f(x)=2 0
  global: 4 0  local: 1 0  local->global: 4 0  jacobian: 4  f(x)=4 0
  global: 4 2  local: 1 1  local->global: 4 2  jacobian: 4  f(x)=4 2
  global: 2 2  local: 0 1  local->global: 2 2  jacobian: 4  f(x)=2 2
Volume=integrate_global(1): 4
integrate_global(coord): 12 4
Center=    3 1
I(center)= 3 1
Cell 3
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.5 2.5
  global: 0 1  local: 0 0  local->global: 0 1  jacobian: 3  f(x)=0 1
  global: 1 1  local: 1 0  local->global: 1 1  jacobian: 3  f(x)=1 1
  global: 1 4  local: 1 1  local->global: 1 4  jacobian: 3  f(x)=1 4
  global: 0 4  local: 0 1  local->global: 0 4  jacobian: 3  f(x)=0 4
Volume=integrate_global(1): 3
integrate_global(coord): 1.5 7.5
Center=    0.5 2.5
I(center)= 0.5 2.5
Cell 4
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 1.5 3
  global: 1 1  local: 0 0  local->global: 1 1  jacobian: 3  f(x)=1 1
  global: 2 2  local: 1 0  local->global: 2 2  jacobian: 3  f(x)=2 2
  global: 2 5  local: 1 1  local->global: 2 5  jacobian: 3  f(x)=2 5
  global: 1 4  local: 0 1  local->global: 1 4  jacobian: 3  f(x)=1 4
Volume=integrate_global(1): 3
integrate_global(coord): 4.5 9
Center=    1.5 3
I(center)= 1.5 3



Cell 0
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.25 0.25
  global: 0 0  local: 0 0  local->global: 0 0  jacobian: 0.25  f(x)=0 0
  global: 0.5 0  local: 1 0  local->global: 0.5 0  jacobian: 0.25  f(x)=0.5 0
  global: 0.5 0.5  local: 1 1  local->global: 0.5 0.5  jacobian: 0.25  f(x)=0.7 0.7
  global: 0 0.5  local: 0 1  local->global: 0 0.5  jacobian: 0.25  f(x)=0 0.5
Volume=integrate_global(1): 0.25
integrate_global(coord): 0.0625 0.0625
Center=    0.25 0.25
I(center)= 0.3 0.3
Cell 1
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.25 0.75
  global: 0 0.5  local: 0 0  local->global: 0 0.5  jacobian: 0.25  f(x)=0 0.5
  global: 0.5 0.5  local: 1 0  local->global: 0.5 0.5  jacobian: 0.25  f(x)=0.7 0.7
  global: 0.5 1  local: 1 1  local->global: 0.5 1  jacobian: 0.25  f(x)=0.5 1
  global: 0 1  local: 0 1  local->global: 0 1  jacobian: 0.25  f(x)=0 1
Volume=integrate_global(1): 0.25
integrate_global(coord): 0.0625 0.1875
Center=    0.25 0.75
I(center)= 0.3 0.8
Cell 2
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.75 0.25
  global: 0.5 0  local: 0 0  local->global: 0.5 0  jacobian: 0.25  f(x)=0.5 0
  global: 1 0  local: 1 0  local->global: 1 0  jacobian: 0.25  f(x)=1 0
  global: 1 0.5  local: 1 1  local->global: 1 0.5  jacobian: 0.25  f(x)=1 0.5
  global: 0.5 0.5  local: 0 1  local->global: 0.5 0.5  jacobian: 0.25  f(x)=0.7 0.7
Volume=integrate_global(1): 0.25
integrate_global(coord): 0.1875 0.0625
Center=    0.75 0.25
I(center)= 0.8 0.3
Cell 3
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.75 0.75
  global: 0.5 0.5  local: 0 0  local->global: 0.5 0.5  jacobian: 0.25  f(x)=0.7 0.7
  global: 1 0.5  local: 1 0  local->global: 1 0.5  jacobian: 0.25  f(x)=1 0.5
  global: 1 1  local: 1 1  local->global: 1 1  jacobian: 0.25  f(x)=1 1
  global: 0.5 1  local: 0 1  local->global: 0.5 1  jacobian: 0.25  f(x)=0.5 1
Volume=integrate_global(1): 0.25
integrate_global(coord): 0.1875 0.1875
Center=    0.75 0.75
I(center)= 0.8 0.8



Cell 0
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 0.5 0.5125 0.525
  global: 0 0 0  local: 0 0 0  local->global: 0 0 0  jacobian: 1  f(x)=0 0 0
  global: 0 0 1  local: 0 0 1  local->global: 0 0 1  jacobian: 1  f(x)=0 0 1
  global: 0 1 0  local: 0 1 0  local->global: 0 1 0  jacobian: 1  f(x)=0 1 0
  global: 0 1 1  local: 0 1 1  local->global: 0 1 1  jacobian: 1  f(x)=0 1 1
  global: 1 0 0  local: 1 0 0  local->global: 1 0 0  jacobian: 1  f(x)=1 0 0
  global: 1 0 1  local: 1 0 1  local->global: 1 0 1  jacobian: 1.1  f(x)=1 0 1
  global: 1 1 0  local: 1 1 0  local->global: 1 1 0  jacobian: 1.2  f(x)=1 1 0
  global: 1 1.1 1.2  local: 1 1 1  local->global: 1 1.1 1.2  jacobian: 1.3  f(x)=1 1.1 1.2
Volume=integrate_global(1): 1.075
integrate_global(coord): 0.5375 0.550937 0.564375
Center=    0.5 0.5125 0.525
I(center)= 0.5 0.5125 0.525
Cell 1
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 0.5 0.5125 1.525
  global: 0 0 1  local: 0 0 0  local->global: 0 0 1  jacobian: 1  f(x)=0 0 1
  global: 0 0 2  local: 0 0 1  local->global: 0 0 2  jacobian: 1  f(x)=0 0 2
  global: 0 1 1  local: 0 1 0  local->global: 0 1 1  jacobian: 1  f(x)=0 1 1
  global: 0 1 2  local: 0 1 1  local->global: 0 1 2  jacobian: 1  f(x)=0 1 2
  global: 1 0 1  local: 1 0 0  local->global: 1 0 1  jacobian: 1.1  f(x)=1 0 1
  global: 1 0 2  local: 1 0 1  local->global: 1 0 2  jacobian: 1  f(x)=1 0 2
  global: 1 1.1 1.2  local: 1 0.999999 -2.40122e-06  local->global: 1 1.1 1.2  jacobian: 0.9  f(x)=1 1.1 1.2
  global: 1 1 2  local: 1 1 1  local->global: 1 1 2  jacobian: 0.8  f(x)=1 1 2
Volume=integrate_global(1): 0.975
integrate_global(coord): 0.4875 0.499687 1.48687
Center=    0.5 0.5125 1.525
I(center)= 0.5 0.5125 1.525
Cell 2
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 0.5 1.5125 0.525
  global: 0 1 0  local: 0 0 0  local->global: 0 1 0  jacobian: 1  f(x)=0 1 0
  global: 0 1 1  local: 0 0 1  local->global: 0 1 1  jacobian: 1  f(x)=0 1 1
  global: 0 2 0  local: 0 1 0  local->global: 0 2 0  jacobian: 1  f(x)=0 2 0
  global: 0 2 1  local: 0 1 1  local->global: 0 2 1  jacobian: 1  f(x)=0 2 1
  global: 1 1 0  local: 1 0 0  local->global: 1 1 0  jacobian: 1.2  f(x)=1 1 0
  global: 1 1.1 1.2  local: 1 -6.46826e-07 0.999999  local->global: 1 1.1 1.2  jacobian: 1.1  f(x)=1 1.1 1.2
  global: 1 2 0  local: 1 1 0  local->global: 1 2 0  jacobian: 1  f(x)=1 2 0
  global: 1 2 1  local: 1 1 1  local->global: 1 2 1  jacobian: 0.9  f(x)=1 2 1
Volume=integrate_global(1): 1.025
integrate_global(coord): 0.5125 1.55031 0.538125
Center=    0.5 1.5125 0.525
I(center)= 0.5 1.5125 0.525
Cell 3
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 0.5 1.5125 1.525
  global: 0 1 1  local: 0 0 0  local->global: 0 1 1  jacobian: 1  f(x)=0 1 1
  global: 0 1 2  local: 0 0 1  local->global: 0 1 2  jacobian: 1  f(x)=0 1 2
  global: 0 2 1  local: 0 1 0  local->global: 0 2 1  jacobian: 1  f(x)=0 2 1
  global: 0 2 2  local: 0 1 1  local->global: 0 2 2  jacobian: 1  f(x)=0 2 2
  global: 1 1.1 1.2  local: 1 0 0  local->global: 1 1.1 1.2  jacobian: 0.7  f(x)=1 1.1 1.2
  global: 1 1 2  local: 1 1.72903e-06 1  local->global: 1 1 2  jacobian: 0.800001  f(x)=1 1 2
  global: 1 2 1  local: 1 1 2.40122e-06  local->global: 1 2 1  jacobian: 0.9  f(x)=1 2 1
  global: 1 2 2  local: 1 1 1  local->global: 1 2 2  jacobian: 1  f(x)=1 2 2
Volume=integrate_global(1): 0.925
integrate_global(coord): 0.4625 1.39906 1.41062
Center=    0.5 1.5125 1.525
I(center)= 0.5 1.5125 1.525
Cell 4
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 1.5 0.5125 0.525
  global: 1 0 0  local: 0 0 0  local->global: 1 0 0  jacobian: 1  f(x)=1 0 0
  global: 1 0 1  local: 0 0 1  local->global: 1 0 1  jacobian: 1.1  f(x)=1 0 1
  global: 1 1 0  local: 0 1 0  local->global: 1 1 0  jacobian: 1.2  f(x)=1 1 0
  global: 1 1.1 1.2  local: 0 1 1  local->global: 1 1.1 1.2  jacobian: 1.3  f(x)=1 1.1 1.2
  global: 2 0 0  local: 1 0 0  local->global: 2 0 0  jacobian: 1  f(x)=2 0 0
  global: 2 0 1  local: 1 0 1  local->global: 2 0 1  jacobian: 1  f(x)=2 0 1
  global: 2 1 0  local: 1 1 0  local->global: 2 1 0  jacobian: 1  f(x)=2 1 0
  global: 2 1 1  local: 1 1 1  local->global: 2 1 1  jacobian: 1  f(x)=2 1 1
Volume=integrate_global(1): 1.075
integrate_global(coord): 1.6125 0.550937 0.564375
Center=    1.5 0.5125 0.525
I(center)= 1.5 0.5125 0.525
Cell 5
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 1.5 0.5125 1.525
  global: 1 0 1  local: 0 0 0  local->global: 1 0 1  jacobian: 1.1  f(x)=1 0 1
  global: 1 0 2  local: 0 0 1  local->global: 1 0 2  jacobian: 1  f(x)=1 0 2
  global: 1 1.1 1.2  local: 0 1 0  local->global: 1 1.1 1.2  jacobian: 0.9  f(x)=1 1.1 1.2
  global: 1 1 2  local: 0 0.999999 0.999998  local->global: 1 0.999999 2  jacobian: 0.8  f(x)=1 0.999999 2
  global: 2 0 1  local: 1 0 0  local->global: 2 0 1  jacobian: 1  f(x)=2 0 1
  global: 2 0 2  local: 1 0 1  local->global: 2 0 2  jacobian: 1  f(x)=2 0 2
  global: 2 1 1  local: 1 1 0  local->global: 2 1 1  jacobian: 1  f(x)=2 1 1
  global: 2 1 2  local: 1 1 1  local->global: 2 1 2  jacobian: 1  f(x)=2 1 2
Volume=integrate_global(1): 0.975
integrate_global(coord): 1.4625 0.499687 1.48687
Center=    1.5 0.5125 1.525
I(center)= 1.5 0.5125 1.525
Cell 6
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 1.5 1.5125 0.525
  global: 1 1 0  local: 0 0 0  local->global: 1 1 0  jacobian: 1.2  f(x)=1 1 0
  global: 1 1.1 1.2  local: 0 0 1  local->global: 1 1.1 1.2  jacobian: 1.1  f(x)=1 1.1 1.2
  global: 1 2 0  local: 0 1 0  local->global: 1 2 0  jacobian: 1  f(x)=1 2 0
  global: 1 2 1  local: 0 1 0.999999  local->global: 1 2 0.999999  jacobian: 0.9  f(x)=1 2 0.999999
  global: 2 1 0  local: 1 0 0  local->global: 2 1 0  jacobian: 1  f(x)=2 1 0
  global: 2 1 1  local: 1 0 1  local->global: 2 1 1  jacobian: 1  f(x)=2 1 1
  global: 2 2 0  local: 1 1 0  local->global: 2 2 0  jacobian: 1  f(x)=2 2 0
  global: 2 2 1  local: 1 1 1  local->global: 2 2 1  jacobian: 1  f(x)=2 2 1
Volume=integrate_global(1): 1.025
integrate_global(coord): 1.5375 1.55031 0.538125
Center=    1.5 1.5125 0.525
I(center)= 1.5 1.5125 0.525
Cell 7
  local cubature point: 0.5 0.5 0.5  weight= 1  global cubature point: 1.5 1.5125 1.525
  global: 1 1.1 1.2  local: 0 0 0  local->global: 1 1.1 1.2  jacobian: 0.7  f(x)=1 1.1 1.2
  global: 1 1 2  local: 0 0 1  local->global: 1 1 2  jacobian: 0.8  f(x)=1 1 2
  global: 1 2 1  local: 0 1 0  local->global: 1 2 1  jacobian: 0.9  f(x)=1 2 1
  global: 1 2 2  local: 0 1 1.00001  local->global: 1 2 2.00001  jacobian: 1  f(x)=1 2 2.00001
  global: 2 1 1  local: 1 0 0  local->global: 2 1 1  jacobian: 1  f(x)=2 1 1
  global: 2 1 2  local: 1 0 1  local->global: 2 1 2  jacobian: 1  f(x)=2 1 2
  global: 2 2 1  local: 1 1 0  local->global: 2 2 1  jacobian: 1  f(x)=2 2 1
  global: 2 2 2  local: 1 1 1  local->global: 2 2 2  jacobian: 1  f(x)=2 2 2
Volume=integrate_global(1): 0.925
integrate_global(coord): 1.3875 1.39906 1.41062
Center=    1.5 1.5125 1.525
I(center)= 1.5 1.5125 1.525
