Cell 0
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.5 0.5
  global: 0 0  local: 0 0  local->global: 0 0  jacobian: 1
  global: 1 0  local: 1 0  local->global: 1 0  jacobian: 1
  global: 1 1  local: 1 1  local->global: 1 1  jacobian: 1
  global: 0 1  local: 0 1  local->global: 0 1  jacobian: 1
Volume=integrate_global(1): 1
integrate_global(coord): 0.5 0.5
Center: 0.5 0.5
Cell 1
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 1.5 0.75
  global: 1 0  local: 0 0  local->global: 1 0  jacobian: 1
  global: 2 0  local: 1 0  local->global: 2 0  jacobian: 2
  global: 2 2  local: 1 1  local->global: 2 2  jacobian: 2
  global: 1 1  local: 0 1  local->global: 1 1  jacobian: 1
Volume=integrate_global(1): 1.5
integrate_global(coord): 2.25 1.125
Center: 1.5 0.75
Cell 2
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 3 1
  global: 2 0  local: 0 0  local->global: 2 0  jacobian: 4
  global: 4 0  local: 1 0  local->global: 4 0  jacobian: 4
  global: 4 2  local: 1 1  local->global: 4 2  jacobian: 4
  global: 2 2  local: 0 1  local->global: 2 2  jacobian: 4
Volume=integrate_global(1): 4
integrate_global(coord): 12 4
Center: 3 1
Cell 3
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 0.5 2.5
  global: 0 1  local: 0 0  local->global: 0 1  jacobian: 3
  global: 1 1  local: 1 0  local->global: 1 1  jacobian: 3
  global: 1 4  local: 1 1  local->global: 1 4  jacobian: 3
  global: 0 4  local: 0 1  local->global: 0 4  jacobian: 3
Volume=integrate_global(1): 3
integrate_global(coord): 1.5 7.5
Center: 0.5 2.5
Cell 4
  local cubature point: 0.5 0.5  weight= 1  global cubature point: 1.5 3
  global: 1 1  local: 0 0  local->global: 1 1  jacobian: 3
  global: 2 2  local: 1 0  local->global: 2 2  jacobian: 3
  global: 2 5  local: 1 1  local->global: 2 5  jacobian: 3
  global: 1 4  local: 0 1  local->global: 1 4  jacobian: 3
Volume=integrate_global(1): 3
integrate_global(coord): 4.5 9
Center: 1.5 3
